My Application: RayCast Class Reference
RayCast Class Reference
Defines the methods and variables for RayCasting.
#include <Raycast.h>
Public Member Functions
RayCast (int Damage, float velocity, Vector3 Position, Vector3 DVector)
~RayCast ()
Constructor.
Vector3 Move ()
Moves the RayCast.
Vector3 Position ()
Calls the current position of each RayCast.
void CalcBounds ()
Calculates the boundary of each RayCast.
Data Fields
float Damage = 0
bool BulletUsed = false
Private Attributes
float Speed = 0
Vector3 StoredDirVec
Vector3 RayPos
Boundary BoundingBox
float increment = 0
Detailed Description
Defines the methods and variables for RayCasting.
Class RayCast:
Definition at line 24 of file Raycast.h.
Constructor & Destructor Documentation
RayCast::RayCast (int Damage, float velocity, Vector3 Position, Vector3 DVector) inline
Definition at line 27 of file Raycast.h.
References CalcBounds().
RayCast::~RayCast ()
Constructor.
Definition at line 20 of file Raycast.cpp.
Member Function Documentation
void RayCast::CalcBounds ()
Calculates the boundary of each RayCast.
Parameters
RayPos - determines the position of the RayCast
Returns
Resulting normalized vectors
Definition at line 59 of file Raycast.cpp.
References BoundingBox, RayPos, Boundary::set(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Move(), and RayCast().
Vector3 RayCast::Move ()
Moves the RayCast.
Parameters
RayPos - determines the position of the RayCast StoredDirVec - returns the value of a stored direction vector Speed - determines the speed of the RayCast
Returns
Resulting normalized vectors
Definition at line 38 of file Raycast.cpp.
References CalcBounds(), RayPos, Speed, StoredDirVec, Vector3::x, Vector3::y, and Vector3::z.
Vector3 RayCast::Position ()
Calls the current position of each RayCast.
Parameters
RayPos - determines the position of the RayCast
Returns
Resulting normalized vectors
Definition at line 75 of file Raycast.cpp.
References RayPos.
Referenced by WeaponSystem::GetLength().
Field Documentation
Boundary RayCast::BoundingBox private
Definition at line 40 of file Raycast.h.
Referenced by CalcBounds().
bool RayCast::BulletUsed = false
Definition at line 34 of file Raycast.h.
float RayCast::Damage = 0
Definition at line 33 of file Raycast.h.
float RayCast::increment = 0 private
Definition at line 41 of file Raycast.h.
Vector3 RayCast::RayPos private
Definition at line 39 of file Raycast.h.
Referenced by CalcBounds(), Move(), and Position().
float RayCast::Speed = 0 private
Definition at line 37 of file Raycast.h.
Referenced by Move().
Vector3 RayCast::StoredDirVec private
Definition at line 38 of file Raycast.h.
Referenced by Move().
The documentation for this class was generated from the following files:
ComGLab/Source/Raycast.h
ComGLab/Source/Raycast.cpp