My Application: irrklang::IFileReader Class Reference
irrklang::IFileReader Class Reference abstract
Interface providing read acess to a file.
#include <ik_IFileReader.h>
Public Member Functions
virtual ~IFileReader ()
virtual ik_s32 read (void *buffer, ik_u32 sizeToRead)=0
Reads an amount of bytes from the file.
virtual bool seek (ik_s32 finalPos, bool relativeMovement=false)=0
Changes position in file, returns true if successful.
virtual ik_s32 getSize ()=0
Returns size of file.
virtual ik_s32 getPos ()=0
Returns the current position in the file.
virtual const ik_c8 * getFileName ()=0
Returns name of file.
Public Member Functions inherited from irrklang::IRefCounted
IRefCounted ()
Constructor.
virtual ~IRefCounted ()
Destructor.
void grab ()
Grabs the object.
bool drop ()
When you receive an object in irrKlang (for example an ISound using play2D() or play3D()), and you no longer need the object, you have to call drop().
Detailed Description
Interface providing read acess to a file.
Definition at line 14 of file ik_IFileReader.h.
Constructor & Destructor Documentation
virtual irrklang::IFileReader::~IFileReader () inline virtual
Definition at line 18 of file ik_IFileReader.h.
Member Function Documentation
virtual const ik_c8* irrklang::IFileReader::getFileName () pure virtual
Returns name of file.
Returns
Returns the file name as zero terminated character string.
virtual ik_s32 irrklang::IFileReader::getPos () pure virtual
Returns the current position in the file.
Returns
Returns the current position in the file in bytes.
Referenced by irrklang::CIrrKlangAudioStreamMP3::CIrrKlangAudioStreamMP3().
virtual ik_s32 irrklang::IFileReader::getSize () pure virtual
Returns size of file.
Returns
Returns the size of the file in bytes.
Referenced by irrklang::CIrrKlangAudioStreamMP3::CIrrKlangAudioStreamMP3().
virtual ik_s32 irrklang::IFileReader::read (void * buffer, ik_u32 sizeToRead) pure virtual
Reads an amount of bytes from the file.
Parameters
buffer Pointer to buffer where to read bytes will be written to.
sizeToRead Amount of bytes to read from the file.
Returns
Returns how much bytes were read.
Referenced by irrklang::CIrrKlangAudioStreamMP3::decodeFrame(), and irrklang::CIrrKlangAudioStreamMP3::skipID3IfNecessary().
virtual bool irrklang::IFileReader::seek (ik_s32 finalPos, bool relativeMovement = false) pure virtual
Changes position in file, returns true if successful.
Parameters
finalPos Destination position in the file.
relativeMovement If set to true, the position in the file is changed relative to current position. Otherwise the position is changed from beginning of file.
Returns
Returns true if successful, otherwise false.
Referenced by irrklang::CIrrKlangAudioStreamMP3::setPosition(), and irrklang::CIrrKlangAudioStreamMP3::skipID3IfNecessary().
The documentation for this class was generated from the following file:
irrKlang-1.5.0/include/ik_IFileReader.h