My Application: SP2_Scene Class Reference
SP2_Scene Class Reference
Defines the methods, enums and variables for SP2_Scene.
#include <SP2_Scene.h>
Public Types
enum Gun_Type {
N_SMG, N_Rifle, N_Sniper, N_Shotgun,
D_Rifle, D_Sniper, D_Shotgun, C_Rifle,
C_Sniper, C_Shotgun, F_Rifle, F_Sniper,
F_Shotgun
}
Public Member Functions
SP2_Scene ()
Constructor.
~SP2_Scene ()
Destructor.
void RenderMesh (Mesh *mesh, bool enableLight)
Method that renders a mesh in the scene.
virtual void Init ()
Initializes values.
virtual void Update (double dt)
Method where values are changed.
virtual void Render (double dt)
Method that renders everything in the game.
virtual void Exit ()
Method that closes the program.
void MothershipBulletSpawner (float BulletDamage, float BulletSpeed, int choice, Vector3 position)
Method that controls the bullets of the enemy mothership.
void InitKeyVariables ()
Holds all the variables used.
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Light light [3]
float tweenVal
float constRotation
float translateX
float scaleAll
float rotationalLimit
float translationLimit
float scalingLimit
float ShipX
float ShipY
float ShipRot
unsigned short repairShipPhase
bool walk
bool moveMship
float moveMshipUp
float rotateMship
bool floatRocks
float moveRocks
bool rLimiter
bool toggleLimiters
bool limitersON
float constTranslation
bool canUseDoor = true
int weaponSelect
bool sniper
bool rifle
unsigned short skyboxID = 0
Position lightDefaultPos
bool lightOff
Camera3 camera
MS modelStack
MS viewStack
MS projectionStack
WeaponSystem EnemyWepSys
RobotManager MothershipHandler
bool Intro = false
bool weaponsOn = false
bool ShipSpawned = false
Vector3 ShipPos1 = Vector3(0, 10, 700)
Vector3 ShipPos2 = Vector3(-60, 40, 700)
Vector3 ShipPos3 = Vector3(60, 40, 700)
float ChoiceTimer = 0
float ShotTimer = 0
float ShipRotation = 90
Boundary PlayerShipBounds
Vector3 PlayerShipCoord
WeaponSystem WepSys
RobotManager RobotManager
bool CanFire = true
float GunWaitTime = 0
int CurrentAmmo = 0
bool IsReloading = false
float ReloadWaitTime = 0
Gun_Type currentGun = N_SMG
float RateOfFire
float Damage = 0
float MaxAmmo = 0
float CurrAmmo = MaxAmmo
bool GameOver = false
Private Types
enum GEOMETRY_TYPE {
GEO_AXES = 0, GEO_QUAD, GEO_CUBE, GEO_CIRCLE,
GEO_RING, GEO_SPHERE, GEO_HEMISPHERE, GEO_TORUS,
GEO_CYLINDER, GEO_CONE, GEO_LEFT, GEO_RIGHT,
GEO_TOP, GEO_BOTTOM, GEO_FRONT, GEO_BACK,
GEO_SMG, GEO_SNIPER, GEO_RIFLE, GEO_SHOTGUN,
GEO_PLAYERSHIP, GEO_MOTHERSHIP, GEO_DRONEBODY, GEO_DRONELEFTUPPERARM,
GEO_DRONELEFTLOWERARM, GEO_DRONERIGHTUPPERARM, GEO_DRONERIGHTLOWERARM, GEO_ROBOTHEALTH,
GEO_ROBOTHEALTH2, GEO_MELEEROBOTBODY, GEO_MELEEROBOTLEFTUPPERARM, GEO_MELEEROBOTLEFTLOWERARM,
GEO_MELEEROBOTRIGHTUPPERARM, GEO_MELEEROBOTRIGHTLOWERARM, GEO_MELEEROBOTRIGHTARM, GEO_MELEEROBOTLEFTLEG,
GEO_MELEEROBOTRIGHTLEG, GEO_RANGEROBOTBODY, GEO_RANGEROBOTLEFTUPPERARM, GEO_RANGEROBOTLEFTLOWERARM,
GEO_RANGEROBOTRIGHTUPPERARM, GEO_RANGEROBOTRIGHTLOWERARM, GEO_RANGEROBOTLEFTLEG, GEO_RANGEROBOTRIGHTLEG,
GEO_MIXEDROBOTBODY, GEO_MIXEDROBOTLEFTUPPERARM, GEO_MIXEDROBOTLEFTLOWERARM, GEO_MIXEDROBOTRIGHTUPPERARM,
GEO_MIXEDROBOTRIGHTLOWERARM, GEO_MIXEDROBOTLEFTLEG, GEO_MIXEDROBOTRIGHTLEG, GEO_GATE,
GEO_METEOR, GEO_CRYSTAL, GEO_CRYSTALBASE, GEO_MOONFLOOR,
GEO_TELEPORTER, GEO_BULLET, GEO_ENEMYBULLET, GEO_TEXT,
GEO_LIGHTBALL, GEO_FLOOR, GEO_BASE, GEO_GATE_SIDE,
GEO_POWERUP, NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION, U_LIGHT2_COLOR,
U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ,
U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER,
U_LIGHT2_EXPONENT, U_NUMLIGHTS, U_TOTAL
}
Private Member Functions
void RenderSkybox (Vector3 Position)
Method that renders the skybox.
void initLights ()
Initializes light settings.
void InitWeaponModels ()
Initializes OBJ and TGA files.
void InitRobots ()
Initializes OBJ and TGA files.
void InitMapModels ()
Initializes OBJ and TGA files.
void initUIElements ()
void readtextfile ()
Reads a text file.
void GameState ()
Method that controls the transition from wave to wave.
void RenderText (Mesh *mesh, std::string text, Color color)
Method that renders text in the scene.
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size=1, float x=0, float y=0)
Method that renders text on screen.
void RenderWeaponInHand (unsigned short wepVal=0, float size=1, float x=0, float y=0)
Method that renders a weapon on screen.
void RenderImageInMap (GLuint texture, float Xsize=1, float Ysize=1)
Method that renders images in the scene.
void RenderImageOnScreen (GLuint texture, float Xsize=1, float Ysize=1, float Xpos=0, float Ypos=0)
method that renders images on screen
void RenderMeshOnScreen (Mesh *mesh, float Xsize=1, float Ysize=1, float Xpos=0, float Ypos=0, float Angle=0, Vector3 RotationDir=Vector3(0, 0, 0))
Method that renders a mesh on screen.
void RenderWepScreen (bool render=false, Vector3 choices=Vector3(0, 0, 0))
Method that renders the weapon select screen.
void RenderTeleporter (bool render=false)
Method that renders the teleporters in the scene.
void RenderGateText (bool render=false)
void RenderRocks ()
Method that renders the rocks in the scene.
void RenderLevel ()
Method that renders text on screen at certain moments in the game.
void initBounds ()
void RenderGate (bool render=false)
void RenderUI ()
Method that renders the user interface.
void RenderShip ()
Method that renders and animates the drivable ship.
void RenderSpaceMap ()
Method that renders the space scene.
void RenderBase ()
Method that renders the base in the scene.
void RenderRobots ()
void RenderPowerUp (unsigned short PowerUpType=1)
Method that renders Power Ups in the scene.
Private Attributes
unsigned short weaponValue
GLuint SB_Day_front
GLuint SB_Day_back
GLuint SB_Day_top
GLuint SB_Day_bottom
GLuint SB_Day_left
GLuint SB_Day_right
GLuint SB_Nite_front
GLuint SB_Nite_back
GLuint SB_Nite_top
GLuint SB_Nite_bottom
GLuint SB_Nite_left
GLuint SB_Nite_right
GLuint Normal_Sniper
GLuint Normal_Rifle
GLuint Normal_SMG
GLuint Damage_Sniper
GLuint Damage_Rifle
GLuint Damage_SMG
GLuint Capacity_Sniper
GLuint Capacity_Rifle
GLuint Capacity_SMG
GLuint Fast_Sniper
GLuint Fast_Rifle
GLuint Fast_SMG
GLuint Crosshair
GLuint Crosshair2
GLuint UI_BG
GLuint UI_HP_Red
GLuint UI_HP_Green
GLuint UI_WepSel_BG
GLuint UI_LoadingBG
GLuint UI_LoadingBarOverlay
GLuint UI_Logo
GLuint Bullet_Red
GLuint Bullet_Teal
GLuint Bullet_Blue
GLuint Bullet_Green
GLuint Bullet_White
unsigned m_vertexArrayID
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Mesh * meshList [NUM_GEOMETRY]
bool buttonPress
float buttonValue
double fps
unsigned int basehp
unsigned int bosshp
unsigned int playerhp
unsigned int ammo
unsigned int wave
float framesPerSecond
Vector3 WepItf_Choices
bool randWepChoices = true
Vector3 spawnPointN
Vector3 spawnPointS
Vector3 spawnPointE
Vector3 spawnPointW
float timer
bool weaponinterface
bool SpawnedRobots = false
bool PlayBGM = false
bool beforeWave7 = false
Vector3 TownLightPosition
Vector3 RoomLightPosition
Vector3 basePosition
Vector3 UICrystalPosition = Vector3(2, 0, 0)
unsigned short UICrystalChoice
bool InMainMenu = false
bool GameStarted = false
bool InSettings = false
float LoadTimer = 0
float MaxLoadTime = 1
bool GameLoading = true
bool loadRobots = false
bool loadMap = false
bool loadWep = false
float explosion
bool PowerUpActive = true
unsigned short PowerUpVal = 0
Detailed Description
Defines the methods, enums and variables for SP2_Scene.
Class Scene:
Definition at line 45 of file SP2_Scene.h.
Member Enumeration Documentation
enum SP2_Scene::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_QUAD
GEO_CUBE
GEO_CIRCLE
GEO_RING
GEO_SPHERE
GEO_HEMISPHERE
GEO_TORUS
GEO_CYLINDER
GEO_CONE
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_SMG
GEO_SNIPER
GEO_RIFLE
GEO_SHOTGUN
GEO_PLAYERSHIP
GEO_MOTHERSHIP
GEO_DRONEBODY
GEO_DRONELEFTUPPERARM
GEO_DRONELEFTLOWERARM
GEO_DRONERIGHTUPPERARM
GEO_DRONERIGHTLOWERARM
GEO_ROBOTHEALTH
GEO_ROBOTHEALTH2
GEO_MELEEROBOTBODY
GEO_MELEEROBOTLEFTUPPERARM
GEO_MELEEROBOTLEFTLOWERARM
GEO_MELEEROBOTRIGHTUPPERARM
GEO_MELEEROBOTRIGHTLOWERARM
GEO_MELEEROBOTRIGHTARM
GEO_MELEEROBOTLEFTLEG
GEO_MELEEROBOTRIGHTLEG
GEO_RANGEROBOTBODY
GEO_RANGEROBOTLEFTUPPERARM
GEO_RANGEROBOTLEFTLOWERARM
GEO_RANGEROBOTRIGHTUPPERARM
GEO_RANGEROBOTRIGHTLOWERARM
GEO_RANGEROBOTLEFTLEG
GEO_RANGEROBOTRIGHTLEG
GEO_MIXEDROBOTBODY
GEO_MIXEDROBOTLEFTUPPERARM
GEO_MIXEDROBOTLEFTLOWERARM
GEO_MIXEDROBOTRIGHTUPPERARM
GEO_MIXEDROBOTRIGHTLOWERARM
GEO_MIXEDROBOTLEFTLEG
GEO_MIXEDROBOTRIGHTLEG
GEO_GATE
GEO_METEOR
GEO_CRYSTAL
GEO_CRYSTALBASE
GEO_MOONFLOOR
GEO_TELEPORTER
GEO_BULLET
GEO_ENEMYBULLET
GEO_TEXT
GEO_LIGHTBALL
GEO_FLOOR
GEO_BASE
GEO_GATE_SIDE
GEO_POWERUP
NUM_GEOMETRY
Definition at line 47 of file SP2_Scene.h.
enum SP2_Scene::Gun_Type
Enumerator
N_SMG
N_Rifle
N_Sniper
N_Shotgun
D_Rifle
D_Sniper
D_Shotgun
C_Rifle
C_Sniper
C_Shotgun
F_Rifle
F_Sniper
F_Shotgun
Definition at line 271 of file SP2_Scene.h.
enum SP2_Scene::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_NUMLIGHTS
U_TOTAL
Definition at line 137 of file SP2_Scene.h.
Constructor & Destructor Documentation
SP2_Scene::SP2_Scene ()
Constructor.
Definition at line 52 of file SP2_Scene.cpp.
SP2_Scene::~SP2_Scene ()
Destructor.
Definition at line 64 of file SP2_Scene.cpp.
Member Function Documentation
void SP2_Scene::Exit () virtual
Method that closes the program.
Implements Scene.
Definition at line 2697 of file SP2_Scene.cpp.
References irrklang::IRefCounted::drop(), m_programID, and m_vertexArrayID.
void SP2_Scene::GameState () private
Method that controls the transition from wave to wave.
Definition at line 960 of file SP2_Scene.cpp.
References basehp, beforeWave7, camera, RobotManager::ClearList(), WeaponSystem::ClearList(), CurrentAmmo, RobotManager::CurrentRobotCount, EnemyWepSys, GameOver, Camera3::Init(), Intro, WeaponSystem::MaxAmmo, Camera3::maxCameraXrotation, Camera3::maxCameraYrotation, Camera3::minCameraXrotation, Camera3::minCameraYrotation, MothershipHandler, irrklang::ISoundEngine::play2D(), PlayBGM, playerhp, PowerUpActive, PowerUpVal, RenderBase(), RenderRocks(), RenderShip(), RenderSpaceMap(), repairShipPhase, RobotManager::RobotList, WeaponSystem::SetStats(), irrklang::ISound::setVolume(), ShipPos1, ShipSpawned, SoundName, Camera3::spaceModeOn, SpawnedRobots, spawnPointE, spawnPointN, spawnPointS, spawnPointW, irrklang::ISound::stop(), wave, weaponinterface, weaponValue, WepSys, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2_Scene::Init () virtual
Initializes values.
Implements Scene.
Definition at line 102 of file SP2_Scene.cpp.
References irrklang::ISoundEngine::addSoundSourceFromFile(), camera, irrklang::createIrrKlangDevice(), MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCircle(), MeshBuilder::GenerateCone(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateCylinder(), MeshBuilder::GenerateHemisphere(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateRing(), MeshBuilder::GenerateSphere(), MeshBuilder::GenerateTorus(), GEO_AXES, GEO_CIRCLE, GEO_CONE, GEO_CUBE, GEO_CYLINDER, GEO_HEMISPHERE, GEO_QUAD, GEO_RING, GEO_SPHERE, GEO_TORUS, Camera3::Init(), initLights(), initUIElements(), MS::LoadMatrix(), LoadShaders(), m_parameters, m_programID, m_vertexArrayID, meshList, projectionStack, S_Height, S_Width, Mtx44::SetToPerspective(), SoundName, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_TEXT_COLOR, and U_TEXT_ENABLED.
void SP2_Scene::initBounds () private
void SP2_Scene::InitKeyVariables ()
Holds all the variables used.
Parameters
tweenVal - value that determines tween constRotation - value that constantly changes with dt constTranslation - value that constantly changes with dt translateX - value that translates along the x-axis scaleAll - value used for scaling rLimiter - boolean used for animation toggleLimiters - boolean used to toggle limiters on limitersOn - boolean that checks if limiters are on lightsOff - boolean that checks if lights are on basehp - value for base hp bosshp - value for boss hp playerhp - value for player hp GameOver - boolean that checks if the game is over wave - value that determines what wave the game is in weaponValue - value that determines what gun is used weaponinterface - boolean that determines if the interface is on screen buttonPress - boolean that checks if a button is pressed or not buttonValue - value that creates a delay between one button press and the next ShipX - value used for translating the drivable ship along the x-axis ShipY - value used for translating the drivable ship along the y-axis ShipRot - value used for rotating the drivable ship repairShipPhase - value used to determine which phase of the repair ship quest the game is in moveRocks - value used to translate rocks floatRocks - boolean that determines if rocks are floating ShipRotation - value used for rotating enemy mothership Intro - boolean that checks if the introductory cutscene is playing weaponsOn - boolean that determines if the mothership is firing at the player ShipSpawned - boolean that determines if the enemy mothership has spawned explosion - value used for animation PowerUpActive - boolean that determines if a Power Up is active WepItf_Choices - Vector3 value for the weapon interface screen SpawnPointN - Vector3 value for a robot spawn point SpawnPointS - Vector3 value for a robot spawn point SpawnPointE - Vector3 value for a robot spawn point SpawnPointW - Vector3 value for a robot spawn point
Definition at line 258 of file SP2_Scene.cpp.
References basehp, bosshp, buttonPress, buttonValue, camera, constRotation, constTranslation, explosion, floatRocks, GameOver, Intro, lightOff, limitersON, Camera3::maxCameraXrotation, Camera3::maxCameraYrotation, Camera3::minCameraXrotation, Camera3::minCameraYrotation, moveRocks, playerhp, PowerUpActive, repairShipPhase, rLimiter, rotationalLimit, scaleAll, scalingLimit, ShipRot, ShipRotation, ShipSpawned, ShipX, ShipY, spawnPointE, spawnPointN, spawnPointS, spawnPointW, toggleLimiters, translateX, translationLimit, tweenVal, wave, weaponinterface, weaponsOn, weaponValue, and WepItf_Choices.
Referenced by Update().
void SP2_Scene::initLights () private
Initializes light settings.
Definition at line 838 of file SP2_Scene.cpp.
References Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_POINT, lightDefaultPos, m_parameters, m_programID, Light::position, Light::power, Position::Set(), Vector3::Set(), Color::Set(), Light::spotDirection, Light::type, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHT1_COLOR, U_LIGHT1_COSCUTOFF, U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT1_KC, U_LIGHT1_KL, U_LIGHT1_KQ, U_LIGHT1_POSITION, U_LIGHT1_POWER, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_TYPE, U_LIGHTENABLED, U_NUMLIGHTS, UICrystalPosition, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
Referenced by Init().
void SP2_Scene::InitMapModels () private
Initializes OBJ and TGA files.
Definition at line 372 of file SP2_Scene.cpp.
References Bullet_White, MeshBuilder::GenerateOBJ(), GEO_BASE, GEO_CRYSTAL, GEO_CRYSTALBASE, GEO_GATE, GEO_METEOR, GEO_MOONFLOOR, GEO_MOTHERSHIP, GEO_POWERUP, GEO_TELEPORTER, LoadTGA(), meshList, and Mesh::textureID.
Referenced by Update().
void SP2_Scene::InitRobots () private
Initializes OBJ and TGA files.
Definition at line 415 of file SP2_Scene.cpp.
References MeshBuilder::GenerateCube(), MeshBuilder::GenerateOBJ(), GEO_DRONEBODY, GEO_DRONELEFTLOWERARM, GEO_DRONELEFTUPPERARM, GEO_DRONERIGHTLOWERARM, GEO_DRONERIGHTUPPERARM, GEO_MELEEROBOTBODY, GEO_MELEEROBOTLEFTLEG, GEO_MELEEROBOTLEFTLOWERARM, GEO_MELEEROBOTLEFTUPPERARM, GEO_MELEEROBOTRIGHTLEG, GEO_MELEEROBOTRIGHTLOWERARM, GEO_MELEEROBOTRIGHTUPPERARM, GEO_MIXEDROBOTBODY, GEO_MIXEDROBOTLEFTLEG, GEO_MIXEDROBOTLEFTLOWERARM, GEO_MIXEDROBOTLEFTUPPERARM, GEO_MIXEDROBOTRIGHTLEG, GEO_MIXEDROBOTRIGHTLOWERARM, GEO_MIXEDROBOTRIGHTUPPERARM, GEO_RANGEROBOTBODY, GEO_RANGEROBOTLEFTLEG, GEO_RANGEROBOTLEFTLOWERARM, GEO_RANGEROBOTLEFTUPPERARM, GEO_RANGEROBOTRIGHTLEG, GEO_RANGEROBOTRIGHTLOWERARM, GEO_RANGEROBOTRIGHTUPPERARM, GEO_ROBOTHEALTH, GEO_ROBOTHEALTH2, LoadTGA(), meshList, and Mesh::textureID.
Referenced by Update().
void SP2_Scene::initUIElements () private
Definition at line 174 of file SP2_Scene.cpp.
References Crosshair, Crosshair2, MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TEXT, GEO_TOP, LoadTGA(), meshList, SB_Day_back, SB_Day_bottom, SB_Day_front, SB_Day_left, SB_Day_right, SB_Day_top, Mesh::textureID, UI_BG, UI_HP_Green, UI_HP_Red, UI_LoadingBarOverlay, UI_LoadingBG, UI_Logo, and UI_WepSel_BG.
Referenced by Init().
void SP2_Scene::InitWeaponModels () private
Initializes OBJ and TGA files.
Definition at line 317 of file SP2_Scene.cpp.
References Bullet_Blue, Bullet_Green, Bullet_Red, Bullet_Teal, Bullet_White, Capacity_Rifle, Capacity_SMG, Capacity_Sniper, Damage_Rifle, Damage_SMG, Damage_Sniper, Fast_Rifle, Fast_SMG, Fast_Sniper, MeshBuilder::GenerateOBJ(), GEO_BULLET, GEO_ENEMYBULLET, GEO_PLAYERSHIP, GEO_RIFLE, GEO_SHOTGUN, GEO_SMG, GEO_SNIPER, LoadTGA(), meshList, Normal_Rifle, Normal_SMG, Normal_Sniper, and Mesh::textureID.
Referenced by Update().
void SP2_Scene::MothershipBulletSpawner (float BulletDamage, float BulletSpeed, int choice, Vector3 position)
Method that controls the bullets of the enemy mothership.
Definition at line 1482 of file SP2_Scene.cpp.
References WeaponSystem::BulletList, EnemyWepSys, PlayerShipCoord, and ShotTimer.
Referenced by Update().
void SP2_Scene::readtextfile () private
Reads a text file.
Definition at line 76 of file SP2_Scene.cpp.
Referenced by Render().
void SP2_Scene::Render (double dt) virtual
Method that renders everything in the game.
Implements Scene.
Definition at line 2424 of file SP2_Scene.cpp.
References basehp, WeaponSystem::BulletList, camera, constRotation, GameLoading, GameOver, GameState(), GEO_BULLET, GEO_CRYSTAL, GEO_RANGEROBOTBODY, GEO_RANGEROBOTLEFTLEG, GEO_RANGEROBOTLEFTLOWERARM, GEO_RANGEROBOTLEFTUPPERARM, GEO_RANGEROBOTRIGHTLEG, GEO_RANGEROBOTRIGHTLOWERARM, GEO_RANGEROBOTRIGHTUPPERARM, GEO_ROBOTHEALTH, GEO_ROBOTHEALTH2, GEO_TEXT, Camera3::getCameraPosition(), InMainMenu, light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, lightOff, MS::LoadIdentity(), loadMap, loadRobots, LoadTimer, loadWep, MS::LookAt(), m_parameters, MaxLoadTime, meshList, modelStack, playerhp, MS::PopMatrix(), Camera::position, Light::position, PowerUpVal, MS::PushMatrix(), readtextfile(), RenderImageInMap(), RenderImageOnScreen(), RenderMesh(), RenderPowerUp(), RenderSkybox(), RenderText(), RenderTextOnScreen(), RenderUI(), RenderWeaponInHand(), RobotManager::RobotList, MS::Rotate(), MS::Scale(), skyboxID, Light::spotDirection, Camera::target, MS::Top(), MS::Translate(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, UI_HP_Green, UI_HP_Red, UI_LoadingBarOverlay, UI_LoadingBG, UI_Logo, UICrystalChoice, UICrystalPosition, Camera::up, viewStack, weaponValue, WepSys, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void SP2_Scene::RenderBase () private
Method that renders the base in the scene.
Definition at line 932 of file SP2_Scene.cpp.
References constRotation, GEO_BASE, GEO_CRYSTAL, GEO_CRYSTALBASE, GEO_MOONFLOOR, GEO_TELEPORTER, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), repairShipPhase, MS::Rotate(), MS::Scale(), MS::Translate(), and tweenVal.
Referenced by GameState().
void SP2_Scene::RenderGate (bool render = false) private
void SP2_Scene::RenderGateText (bool render = false) private
void SP2_Scene::RenderImageInMap (GLuint texture, float Xsize = 1, float Ysize = 1) private
Method that renders images in the scene.
Definition at line 577 of file SP2_Scene.cpp.
References GEO_QUAD, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and Mesh::textureID.
Referenced by Render().
void SP2_Scene::RenderImageOnScreen (GLuint texture, float Xsize = 1, float Ysize = 1, float Xpos = 0, float Ypos = 0) private
method that renders images on screen
Definition at line 598 of file SP2_Scene.cpp.
References GEO_QUAD, MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by Render(), RenderShip(), RenderTeleporter(), RenderUI(), and RenderWepScreen().
void SP2_Scene::RenderLevel () private
Method that renders text on screen at certain moments in the game.
Definition at line 1222 of file SP2_Scene.cpp.
References RobotManager::CurrentRobotCount, GEO_TEXT, meshList, RenderTextOnScreen(), and wave.
void SP2_Scene::RenderMesh (Mesh * mesh, bool enableLight)
Method that renders a mesh in the scene.
Definition at line 788 of file SP2_Scene.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), RenderBase(), RenderImageInMap(), RenderImageOnScreen(), RenderMeshOnScreen(), RenderPowerUp(), RenderRocks(), RenderShip(), RenderSkybox(), RenderSpaceMap(), and RenderWeaponInHand().
void SP2_Scene::RenderMeshOnScreen (Mesh * mesh, float Xsize = 1, float Ysize = 1, float Xpos = 0, float Ypos = 0, float Angle = 0, Vector3 RotationDir = Vector3(0, 0, 0)) private
Method that renders a mesh on screen.
Definition at line 760 of file SP2_Scene.cpp.
References MS::LoadIdentity(), MS::LoadMatrix(), modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), MS::Translate(), viewStack, Vector3::x, Vector3::y, and Vector3::z.
Referenced by RenderWepScreen().
void SP2_Scene::RenderPowerUp (unsigned short PowerUpType = 1) private
Method that renders Power Ups in the scene.
Definition at line 1104 of file SP2_Scene.cpp.
References Boundary::BoundaryCheck(), Bullet_Blue, Bullet_Green, Bullet_Red, camera, WeaponSystem::ClearList(), constRotation, CurrentAmmo, GEO_POWERUP, GEO_TORUS, Camera3::getCameraPosition(), WeaponSystem::MaxAmmo, meshList, modelStack, MS::PopMatrix(), Camera3::PowerUp, PowerUpActive, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), WeaponSystem::SetStats(), Mesh::textureID, MS::Translate(), weaponValue, WepSys, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2_Scene::RenderRobots () private
void SP2_Scene::RenderRocks () private
Method that renders the rocks in the scene.
Definition at line 2391 of file SP2_Scene.cpp.
References Math::DegreeToRadian(), GEO_METEOR, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), and MS::Translate().
Referenced by GameState().
void SP2_Scene::RenderShip () private
Method that renders and animates the drivable ship.
Definition at line 1419 of file SP2_Scene.cpp.
References camera, Camera3::CameraYrotation, Camera3::coreCheck, GEO_PLAYERSHIP, GEO_TEXT, Camera3::Init(), meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderImageOnScreen(), RenderMesh(), RenderTextOnScreen(), repairShipPhase, MS::Rotate(), MS::Scale(), Camera3::shipCheck, ShipRot, ShipX, ShipY, MS::Translate(), UI_BG, and weaponValue.
Referenced by GameState().
void SP2_Scene::RenderSkybox (Vector3 Position) private
Method that renders the skybox.
Definition at line 2098 of file SP2_Scene.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2_Scene::RenderSpaceMap () private
Method that renders the space scene.
Definition at line 1279 of file SP2_Scene.cpp.
References WeaponSystem::BulletList, Math::DegreeToRadian(), EnemyWepSys, GEO_ENEMYBULLET, GEO_METEOR, GEO_MOTHERSHIP, GEO_PLAYERSHIP, meshList, modelStack, MothershipHandler, moveRocks, PlayerShipCoord, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), RobotManager::RobotList, MS::Rotate(), MS::Scale(), ShipRotation, MS::Translate(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by GameState().
void SP2_Scene::RenderTeleporter (bool render = false) private
Method that renders the teleporters in the scene.
Definition at line 2277 of file SP2_Scene.cpp.
References GEO_TEXT, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderImageOnScreen(), RenderTextOnScreen(), and UI_BG.
Referenced by RenderUI().
void SP2_Scene::RenderText (Mesh * mesh, std::string text, Color color) private
Method that renders text in the scene.
Definition at line 492 of file SP2_Scene.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render().
void SP2_Scene::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size = 1, float x = 0, float y = 0) private
Method that renders text on screen.
Definition at line 527 of file SP2_Scene.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
Referenced by Render(), RenderLevel(), RenderShip(), RenderTeleporter(), RenderUI(), and RenderWepScreen().
void SP2_Scene::RenderUI () private
Method that renders the user interface.
Definition at line 2295 of file SP2_Scene.cpp.
References camera, Crosshair, CurrentAmmo, framesPerSecond, GEO_TEXT, Camera3::getCameraPosition(), IsReloading, WeaponSystem::MaxAmmo, meshList, modelStack, MothershipHandler, pause, playerhp, MS::PopMatrix(), MS::PushMatrix(), WeaponSystem::ReloadTime, ReloadWaitTime, RenderImageOnScreen(), RenderTeleporter(), RenderTextOnScreen(), RenderWeaponInHand(), RenderWepScreen(), repairShipPhase, RobotManager::RobotList, ShipSpawned, Camera3::teleCheck, UI_BG, UI_HP_Green, UI_HP_Red, wave, weaponinterface, weaponValue, WepItf_Choices, WepSys, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Render().
void SP2_Scene::RenderWeaponInHand (unsigned short wepVal = 0, float size = 1, float x = 0, float y = 0) private
Method that renders a weapon on screen.
Definition at line 632 of file SP2_Scene.cpp.
References Bullet_Blue, Bullet_Green, Bullet_Red, Bullet_Teal, Bullet_White, Capacity_Rifle, Capacity_SMG, Capacity_Sniper, Damage_Rifle, Damage_SMG, Damage_Sniper, Fast_Rifle, Fast_SMG, Fast_Sniper, GEO_BULLET, GEO_CRYSTAL, GEO_RIFLE, GEO_SMG, GEO_SNIPER, MS::LoadIdentity(), MS::LoadMatrix(), meshList, modelStack, Normal_Rifle, Normal_SMG, Normal_Sniper, MS::PopMatrix(), projectionStack, MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), Mtx44::SetToOrtho(), Mesh::textureID, MS::Translate(), and viewStack.
Referenced by Render(), and RenderUI().
void SP2_Scene::RenderWepScreen (bool render = false, Vector3 choices = Vector3(0, 0, 0)) private
Method that renders the weapon select screen.
Definition at line 2161 of file SP2_Scene.cpp.
References Capacity_Rifle, Capacity_SMG, Capacity_Sniper, constRotation, Damage_Rifle, Damage_SMG, Damage_Sniper, Fast_Rifle, Fast_SMG, Fast_Sniper, GEO_RIFLE, GEO_SMG, GEO_SNIPER, GEO_TEXT, meshList, modelStack, Normal_Rifle, Normal_SMG, Normal_Sniper, pause, MS::PopMatrix(), MS::PushMatrix(), RenderImageOnScreen(), RenderMeshOnScreen(), RenderTextOnScreen(), Mesh::textureID, UI_BG, UI_WepSel_BG, Vector3::x, Vector3::y, and Vector3::z.
Referenced by RenderUI().
void SP2_Scene::Update (double dt) virtual
Method where values are changed.
Implements Scene.
Definition at line 1523 of file SP2_Scene.cpp.
References basehp, Camera3::baseWalkSpeed, Boundary::BoundaryCheck(), WeaponSystem::BulletList, buttonPress, buttonValue, camera, Camera3::CameraXrotation, CanFire, Camera3::CanMoveCamera, ChoiceTimer, WeaponSystem::CleanUp(), RobotManager::CleanUp(), WeaponSystem::ClearList(), Application::CloseGame, Light::color, constRotation, constTranslation, Camera3::coreCheck, CurrentAmmo, WeaponSystem::Damage, EnemyWepSys, floatRocks, framesPerSecond, GameLoading, GameOver, GameStarted, Camera3::getCameraPosition(), Camera3::getLookVector(), GunWaitTime, WeaponSystem::IncrementPosition(), RobotManager::IncrementPosition(), Camera3::Init(), InitKeyVariables(), InitMapModels(), InitRobots(), InitWeaponModels(), InMainMenu, InSettings, Intro, Application::IsKeyPressed(), IsReloading, light, loadMap, MS::LoadMatrix(), loadRobots, LoadTimer, loadWep, m_parameters, WeaponSystem::MaxAmmo, Camera3::maxCameraXrotation, Camera3::maxCameraYrotation, MaxLoadTime, Camera3::minCameraXrotation, Camera3::minCameraYrotation, MothershipBulletSpawner(), MothershipHandler, moveMship, moveMshipUp, moveRocks, pause, irrklang::ISoundEngine::play2D(), PlayBGM, playerhp, PlayerShipBounds, PlayerShipCoord, Light::position, projectionStack, randWepChoices, WeaponSystem::RateOfFire, WeaponSystem::ReloadTime, ReloadWaitTime, repairShipPhase, Camera3::Reset(), rLimiter, RobotManager::RobotList, RoomLightPosition, rotateMship, rotationalLimit, S_Height, S_Width, scaleAll, scalingLimit, Boundary::set(), Position::Set(), Color::Set(), WeaponSystem::SetStats(), Mtx44::SetToPerspective(), irrklang::ISound::setVolume(), Camera3::shipCheck, ShipPos1, ShipPos2, ShipPos3, ShipRot, ShipRotation, ShipSpawned, ShipX, ShipY, ShotTimer, SoundName, Camera3::spaceModeOn, SpawnedRobots, WeaponSystem::Speed, irrklang::ISound::stop(), TownLightPosition, translateX, translationLimit, tweenVal, U_LIGHT0_COLOR, U_LIGHT1_COLOR, UICrystalChoice, UICrystalPosition, Camera3::Update(), wave, weaponinterface, weaponsOn, weaponValue, WepItf_Choices, WepSys, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
unsigned int SP2_Scene::ammo private
Definition at line 356 of file SP2_Scene.h.
unsigned int SP2_Scene::basehp private
Definition at line 353 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), Render(), and Update().
Vector3 SP2_Scene::basePosition private
Definition at line 383 of file SP2_Scene.h.
bool SP2_Scene::beforeWave7 = false private
Definition at line 375 of file SP2_Scene.h.
Referenced by GameState().
unsigned int SP2_Scene::bosshp private
Definition at line 354 of file SP2_Scene.h.
Referenced by InitKeyVariables().
GLuint SP2_Scene::Bullet_Blue private
Definition at line 308 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderPowerUp(), and RenderWeaponInHand().
GLuint SP2_Scene::Bullet_Green private
Definition at line 308 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderPowerUp(), and RenderWeaponInHand().
GLuint SP2_Scene::Bullet_Red private
Definition at line 308 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderPowerUp(), and RenderWeaponInHand().
GLuint SP2_Scene::Bullet_Teal private
Definition at line 308 of file SP2_Scene.h.
Referenced by InitWeaponModels(), and RenderWeaponInHand().
GLuint SP2_Scene::Bullet_White private
Definition at line 308 of file SP2_Scene.h.
Referenced by InitMapModels(), InitWeaponModels(), and RenderWeaponInHand().
bool SP2_Scene::buttonPress private
Definition at line 348 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
float SP2_Scene::buttonValue private
Definition at line 349 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
Camera3 SP2_Scene::camera
Definition at line 242 of file SP2_Scene.h.
Referenced by GameState(), Init(), InitKeyVariables(), Render(), RenderPowerUp(), RenderShip(), RenderUI(), and Update().
bool SP2_Scene::CanFire = true
Definition at line 266 of file SP2_Scene.h.
Referenced by Update().
bool SP2_Scene::canUseDoor = true
Definition at line 232 of file SP2_Scene.h.
GLuint SP2_Scene::Capacity_Rifle private
Definition at line 303 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Capacity_SMG private
Definition at line 303 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Capacity_Sniper private
Definition at line 303 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
float SP2_Scene::ChoiceTimer = 0
Definition at line 255 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::constRotation
Definition at line 210 of file SP2_Scene.h.
Referenced by InitKeyVariables(), Render(), RenderBase(), RenderPowerUp(), RenderWepScreen(), and Update().
float SP2_Scene::constTranslation
Definition at line 231 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
GLuint SP2_Scene::Crosshair private
Definition at line 305 of file SP2_Scene.h.
Referenced by initUIElements(), and RenderUI().
GLuint SP2_Scene::Crosshair2 private
Definition at line 305 of file SP2_Scene.h.
Referenced by initUIElements().
float SP2_Scene::CurrAmmo = MaxAmmo
Definition at line 291 of file SP2_Scene.h.
int SP2_Scene::CurrentAmmo = 0
Definition at line 268 of file SP2_Scene.h.
Referenced by GameState(), RenderPowerUp(), RenderUI(), and Update().
Gun_Type SP2_Scene::currentGun = N_SMG
Definition at line 287 of file SP2_Scene.h.
float SP2_Scene::Damage = 0
Definition at line 289 of file SP2_Scene.h.
GLuint SP2_Scene::Damage_Rifle private
Definition at line 302 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Damage_SMG private
Definition at line 302 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Damage_Sniper private
Definition at line 302 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
WeaponSystem SP2_Scene::EnemyWepSys
Definition at line 247 of file SP2_Scene.h.
Referenced by GameState(), MothershipBulletSpawner(), RenderSpaceMap(), and Update().
float SP2_Scene::explosion private
Definition at line 401 of file SP2_Scene.h.
Referenced by InitKeyVariables().
GLuint SP2_Scene::Fast_Rifle private
Definition at line 304 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Fast_SMG private
Definition at line 304 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Fast_Sniper private
Definition at line 304 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
bool SP2_Scene::floatRocks
Definition at line 225 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
double SP2_Scene::fps private
Definition at line 352 of file SP2_Scene.h.
float SP2_Scene::framesPerSecond private
Definition at line 358 of file SP2_Scene.h.
Referenced by RenderUI(), and Update().
bool SP2_Scene::GameLoading = true private
Definition at line 395 of file SP2_Scene.h.
Referenced by Render(), and Update().
bool SP2_Scene::GameOver = false
Definition at line 293 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), Render(), and Update().
bool SP2_Scene::GameStarted = false private
Definition at line 389 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::GunWaitTime = 0
Definition at line 267 of file SP2_Scene.h.
Referenced by Update().
bool SP2_Scene::InMainMenu = false private
Definition at line 388 of file SP2_Scene.h.
Referenced by Render(), and Update().
bool SP2_Scene::InSettings = false private
Definition at line 390 of file SP2_Scene.h.
Referenced by Update().
bool SP2_Scene::Intro = false
Definition at line 249 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), and Update().
bool SP2_Scene::IsReloading = false
Definition at line 269 of file SP2_Scene.h.
Referenced by RenderUI(), and Update().
Light SP2_Scene::light[3]
Definition at line 202 of file SP2_Scene.h.
Referenced by initLights(), Render(), and Update().
Position SP2_Scene::lightDefaultPos
Definition at line 238 of file SP2_Scene.h.
Referenced by initLights().
bool SP2_Scene::lightOff
Definition at line 240 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Render().
bool SP2_Scene::limitersON
Definition at line 230 of file SP2_Scene.h.
Referenced by InitKeyVariables().
bool SP2_Scene::loadMap = false private
Definition at line 397 of file SP2_Scene.h.
Referenced by Render(), and Update().
bool SP2_Scene::loadRobots = false private
Definition at line 396 of file SP2_Scene.h.
Referenced by Render(), and Update().
float SP2_Scene::LoadTimer = 0 private
Definition at line 393 of file SP2_Scene.h.
Referenced by Render(), and Update().
bool SP2_Scene::loadWep = false private
Definition at line 398 of file SP2_Scene.h.
Referenced by Render(), and Update().
unsigned SP2_Scene::m_parameters[U_TOTAL] private
Definition at line 313 of file SP2_Scene.h.
Referenced by Init(), initLights(), Render(), RenderMesh(), RenderText(), RenderTextOnScreen(), and Update().
unsigned SP2_Scene::m_programID private
Definition at line 312 of file SP2_Scene.h.
Referenced by Exit(), Init(), and initLights().
unsigned SP2_Scene::m_vertexArrayID private
Definition at line 311 of file SP2_Scene.h.
Referenced by Exit(), and Init().
float SP2_Scene::MaxAmmo = 0
Definition at line 290 of file SP2_Scene.h.
float SP2_Scene::MaxLoadTime = 1 private
Definition at line 394 of file SP2_Scene.h.
Referenced by Render(), and Update().
Mesh* SP2_Scene::meshList[NUM_GEOMETRY] private
Definition at line 314 of file SP2_Scene.h.
Referenced by Init(), InitMapModels(), InitRobots(), initUIElements(), InitWeaponModels(), Render(), RenderBase(), RenderImageInMap(), RenderImageOnScreen(), RenderLevel(), RenderPowerUp(), RenderRocks(), RenderShip(), RenderSkybox(), RenderSpaceMap(), RenderTeleporter(), RenderUI(), RenderWeaponInHand(), and RenderWepScreen().
MS SP2_Scene::modelStack
Definition at line 244 of file SP2_Scene.h.
Referenced by Render(), RenderBase(), RenderImageInMap(), RenderImageOnScreen(), RenderMesh(), RenderMeshOnScreen(), RenderPowerUp(), RenderRocks(), RenderShip(), RenderSkybox(), RenderSpaceMap(), RenderTeleporter(), RenderText(), RenderTextOnScreen(), RenderUI(), RenderWeaponInHand(), and RenderWepScreen().
RobotManager SP2_Scene::MothershipHandler
Definition at line 248 of file SP2_Scene.h.
Referenced by GameState(), RenderSpaceMap(), RenderUI(), and Update().
bool SP2_Scene::moveMship
Definition at line 222 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::moveMshipUp
Definition at line 223 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::moveRocks
Definition at line 226 of file SP2_Scene.h.
Referenced by InitKeyVariables(), RenderSpaceMap(), and Update().
GLuint SP2_Scene::Normal_Rifle private
Definition at line 301 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Normal_SMG private
Definition at line 301 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
GLuint SP2_Scene::Normal_Sniper private
Definition at line 301 of file SP2_Scene.h.
Referenced by InitWeaponModels(), RenderWeaponInHand(), and RenderWepScreen().
bool SP2_Scene::PlayBGM = false private
Definition at line 374 of file SP2_Scene.h.
Referenced by GameState(), and Update().
unsigned int SP2_Scene::playerhp private
Definition at line 355 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), Render(), RenderUI(), and Update().
Boundary SP2_Scene::PlayerShipBounds
Definition at line 258 of file SP2_Scene.h.
Referenced by Update().
Vector3 SP2_Scene::PlayerShipCoord
Definition at line 259 of file SP2_Scene.h.
Referenced by MothershipBulletSpawner(), RenderSpaceMap(), and Update().
bool SP2_Scene::PowerUpActive = true private
Definition at line 404 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), and RenderPowerUp().
unsigned short SP2_Scene::PowerUpVal = 0 private
Definition at line 405 of file SP2_Scene.h.
Referenced by GameState(), and Render().
MS SP2_Scene::projectionStack
Definition at line 244 of file SP2_Scene.h.
Referenced by Init(), RenderImageOnScreen(), RenderMesh(), RenderMeshOnScreen(), RenderText(), RenderTextOnScreen(), RenderWeaponInHand(), and Update().
bool SP2_Scene::randWepChoices = true private
Definition at line 362 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::RateOfFire
Definition at line 288 of file SP2_Scene.h.
float SP2_Scene::ReloadWaitTime = 0
Definition at line 270 of file SP2_Scene.h.
Referenced by RenderUI(), and Update().
unsigned short SP2_Scene::repairShipPhase
Definition at line 219 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), RenderBase(), RenderShip(), RenderUI(), and Update().
bool SP2_Scene::rifle
Definition at line 234 of file SP2_Scene.h.
bool SP2_Scene::rLimiter
Definition at line 228 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
RobotManager SP2_Scene::RobotManager
Definition at line 263 of file SP2_Scene.h.
Vector3 SP2_Scene::RoomLightPosition private
Definition at line 380 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::rotateMship
Definition at line 224 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::rotationalLimit
Definition at line 213 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
GLuint SP2_Scene::SB_Day_back private
Definition at line 299 of file SP2_Scene.h.
Referenced by initUIElements().
GLuint SP2_Scene::SB_Day_bottom private
Definition at line 299 of file SP2_Scene.h.
Referenced by initUIElements().
GLuint SP2_Scene::SB_Day_front private
Definition at line 299 of file SP2_Scene.h.
Referenced by initUIElements().
GLuint SP2_Scene::SB_Day_left private
Definition at line 299 of file SP2_Scene.h.
Referenced by initUIElements().
GLuint SP2_Scene::SB_Day_right private
Definition at line 299 of file SP2_Scene.h.
Referenced by initUIElements().
GLuint SP2_Scene::SB_Day_top private
Definition at line 299 of file SP2_Scene.h.
Referenced by initUIElements().
GLuint SP2_Scene::SB_Nite_back private
Definition at line 300 of file SP2_Scene.h.
GLuint SP2_Scene::SB_Nite_bottom private
Definition at line 300 of file SP2_Scene.h.
GLuint SP2_Scene::SB_Nite_front private
Definition at line 300 of file SP2_Scene.h.
GLuint SP2_Scene::SB_Nite_left private
Definition at line 300 of file SP2_Scene.h.
GLuint SP2_Scene::SB_Nite_right private
Definition at line 300 of file SP2_Scene.h.
GLuint SP2_Scene::SB_Nite_top private
Definition at line 300 of file SP2_Scene.h.
float SP2_Scene::scaleAll
Definition at line 212 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
float SP2_Scene::scalingLimit
Definition at line 215 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
Vector3 SP2_Scene::ShipPos1 = Vector3(0, 10, 700)
Definition at line 252 of file SP2_Scene.h.
Referenced by GameState(), and Update().
Vector3 SP2_Scene::ShipPos2 = Vector3(-60, 40, 700)
Definition at line 253 of file SP2_Scene.h.
Referenced by Update().
Vector3 SP2_Scene::ShipPos3 = Vector3(60, 40, 700)
Definition at line 254 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::ShipRot
Definition at line 218 of file SP2_Scene.h.
Referenced by InitKeyVariables(), RenderShip(), and Update().
float SP2_Scene::ShipRotation = 90
Definition at line 257 of file SP2_Scene.h.
Referenced by InitKeyVariables(), RenderSpaceMap(), and Update().
bool SP2_Scene::ShipSpawned = false
Definition at line 251 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), RenderUI(), and Update().
float SP2_Scene::ShipX
Definition at line 216 of file SP2_Scene.h.
Referenced by InitKeyVariables(), RenderShip(), and Update().
float SP2_Scene::ShipY
Definition at line 217 of file SP2_Scene.h.
Referenced by InitKeyVariables(), RenderShip(), and Update().
float SP2_Scene::ShotTimer = 0
Definition at line 256 of file SP2_Scene.h.
Referenced by MothershipBulletSpawner(), and Update().
unsigned short SP2_Scene::skyboxID = 0
Definition at line 236 of file SP2_Scene.h.
Referenced by Render().
bool SP2_Scene::sniper
Definition at line 234 of file SP2_Scene.h.
bool SP2_Scene::SpawnedRobots = false private
Definition at line 373 of file SP2_Scene.h.
Referenced by GameState(), and Update().
Vector3 SP2_Scene::spawnPointE private
Definition at line 367 of file SP2_Scene.h.
Referenced by GameState(), and InitKeyVariables().
Vector3 SP2_Scene::spawnPointN private
Definition at line 365 of file SP2_Scene.h.
Referenced by GameState(), and InitKeyVariables().
Vector3 SP2_Scene::spawnPointS private
Definition at line 366 of file SP2_Scene.h.
Referenced by GameState(), and InitKeyVariables().
Vector3 SP2_Scene::spawnPointW private
Definition at line 368 of file SP2_Scene.h.
Referenced by GameState(), and InitKeyVariables().
float SP2_Scene::timer private
Definition at line 371 of file SP2_Scene.h.
bool SP2_Scene::toggleLimiters
Definition at line 229 of file SP2_Scene.h.
Referenced by InitKeyVariables().
Vector3 SP2_Scene::TownLightPosition private
Definition at line 379 of file SP2_Scene.h.
Referenced by Update().
float SP2_Scene::translateX
Definition at line 211 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
float SP2_Scene::translationLimit
Definition at line 214 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
float SP2_Scene::tweenVal
Definition at line 209 of file SP2_Scene.h.
Referenced by InitKeyVariables(), RenderBase(), and Update().
GLuint SP2_Scene::UI_BG private
Definition at line 306 of file SP2_Scene.h.
Referenced by initUIElements(), RenderShip(), RenderTeleporter(), RenderUI(), and RenderWepScreen().
GLuint SP2_Scene::UI_HP_Green private
Definition at line 306 of file SP2_Scene.h.
Referenced by initUIElements(), Render(), and RenderUI().
GLuint SP2_Scene::UI_HP_Red private
Definition at line 306 of file SP2_Scene.h.
Referenced by initUIElements(), Render(), and RenderUI().
GLuint SP2_Scene::UI_LoadingBarOverlay private
Definition at line 306 of file SP2_Scene.h.
Referenced by initUIElements(), and Render().
GLuint SP2_Scene::UI_LoadingBG private
Definition at line 306 of file SP2_Scene.h.
Referenced by initUIElements(), and Render().
GLuint SP2_Scene::UI_Logo private
Definition at line 307 of file SP2_Scene.h.
Referenced by initUIElements(), and Render().
GLuint SP2_Scene::UI_WepSel_BG private
Definition at line 306 of file SP2_Scene.h.
Referenced by initUIElements(), and RenderWepScreen().
unsigned short SP2_Scene::UICrystalChoice private
Definition at line 387 of file SP2_Scene.h.
Referenced by Render(), and Update().
Vector3 SP2_Scene::UICrystalPosition = Vector3(2, 0, 0) private
Definition at line 386 of file SP2_Scene.h.
Referenced by initLights(), Render(), and Update().
MS SP2_Scene::viewStack
Definition at line 244 of file SP2_Scene.h.
Referenced by Render(), RenderImageOnScreen(), RenderMesh(), RenderMeshOnScreen(), RenderText(), RenderTextOnScreen(), and RenderWeaponInHand().
bool SP2_Scene::walk
Definition at line 220 of file SP2_Scene.h.
unsigned int SP2_Scene::wave private
Definition at line 357 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), RenderLevel(), RenderUI(), and Update().
bool SP2_Scene::weaponinterface private
Definition at line 372 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), RenderUI(), and Update().
int SP2_Scene::weaponSelect
Definition at line 233 of file SP2_Scene.h.
bool SP2_Scene::weaponsOn = false
Definition at line 250 of file SP2_Scene.h.
Referenced by InitKeyVariables(), and Update().
unsigned short SP2_Scene::weaponValue private
Definition at line 298 of file SP2_Scene.h.
Referenced by GameState(), InitKeyVariables(), Render(), RenderPowerUp(), RenderShip(), RenderUI(), and Update().
Vector3 SP2_Scene::WepItf_Choices private
Definition at line 361 of file SP2_Scene.h.
Referenced by InitKeyVariables(), RenderUI(), and Update().
WeaponSystem SP2_Scene::WepSys
Definition at line 262 of file SP2_Scene.h.
Referenced by GameState(), Render(), RenderPowerUp(), RenderUI(), and Update().
The documentation for this class was generated from the following files:
ComGLab/Source/SP2_Scene.h
ComGLab/Source/SP2_Scene.cpp