My Application: irrklang::CIrrKlangAudioStreamMP3::QueueBuffer Class Reference
irrklang::CIrrKlangAudioStreamMP3::QueueBuffer Class Reference
#include <CIrrKlangAudioStreamMP3.h>
Public Member Functions
QueueBuffer ()
~QueueBuffer ()
int getSize ()
void write (const void *buffer, int size)
int read (void *buffer, int size)
void clear ()
Private Attributes
ik_u8 * Buffer
int Capacity
int Size
Detailed Description
Definition at line 74 of file CIrrKlangAudioStreamMP3.h.
Constructor & Destructor Documentation
irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::QueueBuffer ()
Definition at line 309 of file CIrrKlangAudioStreamMP3.cpp.
References Buffer, Capacity, and Size.
irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::~QueueBuffer ()
Definition at line 318 of file CIrrKlangAudioStreamMP3.cpp.
Member Function Documentation
void irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::clear ()
Definition at line 360 of file CIrrKlangAudioStreamMP3.cpp.
Referenced by irrklang::CIrrKlangAudioStreamMP3::setPosition().
int irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::getSize ()
Definition at line 323 of file CIrrKlangAudioStreamMP3.cpp.
Referenced by irrklang::CIrrKlangAudioStreamMP3::readFrames().
int irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::read (void * buffer, int size)
Definition at line 348 of file CIrrKlangAudioStreamMP3.cpp.
Referenced by irrklang::CIrrKlangAudioStreamMP3::readFrames().
void irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::write (const void * buffer, int size)
Definition at line 328 of file CIrrKlangAudioStreamMP3.cpp.
Referenced by irrklang::CIrrKlangAudioStreamMP3::decodeFrame().
Field Documentation
ik_u8* irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::Buffer private
Definition at line 88 of file CIrrKlangAudioStreamMP3.h.
Referenced by QueueBuffer().
int irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::Capacity private
Definition at line 89 of file CIrrKlangAudioStreamMP3.h.
Referenced by QueueBuffer().
int irrklang::CIrrKlangAudioStreamMP3::QueueBuffer::Size private
Definition at line 90 of file CIrrKlangAudioStreamMP3.h.
Referenced by QueueBuffer().
The documentation for this class was generated from the following files:
irrKlang-1.5.0/plugins/ikpMP3/CIrrKlangAudioStreamMP3.h
irrKlang-1.5.0/plugins/ikpMP3/CIrrKlangAudioStreamMP3.cpp