My Application: Particle Class Reference
Particle Class Reference
#include <Particle.h>
Public Member Functions
Particle ()
~Particle ()
void RenderMesh (Mesh *mesh, bool enableLight)
virtual void Init ()
virtual void Update (double dt)
virtual void Render (double dt)
virtual void Exit ()
Public Member Functions inherited from Scene
Scene ()
~Scene ()
Data Fields
Light light [3]
float tweenVal
float constRotation
float translateX
float scaleAll
float rotationalLimit
float translationLimit
float scalingLimit
bool rLimiter
bool toggleLimiters
bool limitersON
float constTranslation
float DoorRot
bool canUseDoor = true
unsigned short skyboxID = 0
Position lightDefaultPos
bool lightOff
Camera3 camera
MS modelStack
MS viewStack
MS projectionStack
Private Types
enum GEOMETRY_TYPE {
GEO_AXES = 0, GEO_QUAD, GEO_CUBE, GEO_CIRCLE,
GEO_RING, GEO_SPHERE, GEO_HEMISPHERE, GEO_TORUS,
GEO_CYLINDER, GEO_CONE, GEO_LEFT, GEO_RIGHT,
GEO_TOP, GEO_BOTTOM, GEO_FRONT, GEO_BACK,
GEO_SNIPER, GEO_TEXT, GEO_LIGHTBALL, GEO_FLOOR,
NUM_GEOMETRY
}
enum UNIFORM_TYPE {
U_MVP = 0, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MATERIAL_AMBIENT,
U_MATERIAL_DIFFUSE, U_MATERIAL_SPECULAR, U_MATERIAL_SHININESS, U_COLOR_TEXTURE_ENABLED,
U_COLOR_TEXTURE, U_TEXT_ENABLED, U_TEXT_COLOR, U_LIGHT0_POSITION,
U_LIGHT0_COLOR, U_LIGHT0_POWER, U_LIGHT0_KC, U_LIGHT0_KL,
U_LIGHT0_KQ, U_LIGHTENABLED, U_LIGHT0_TYPE, U_LIGHT0_SPOTDIRECTION,
U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT1_POSITION,
U_LIGHT1_COLOR, U_LIGHT1_POWER, U_LIGHT1_KC, U_LIGHT1_KL,
U_LIGHT1_KQ, U_LIGHT1_TYPE, U_LIGHT1_SPOTDIRECTION, U_LIGHT1_COSCUTOFF,
U_LIGHT1_COSINNER, U_LIGHT1_EXPONENT, U_LIGHT2_POSITION, U_LIGHT2_COLOR,
U_LIGHT2_POWER, U_LIGHT2_KC, U_LIGHT2_KL, U_LIGHT2_KQ,
U_LIGHT2_TYPE, U_LIGHT2_SPOTDIRECTION, U_LIGHT2_COSCUTOFF, U_LIGHT2_COSINNER,
U_LIGHT2_EXPONENT, U_NUMLIGHTS, U_TOTAL
}
Private Member Functions
void RenderSkybox (Vector3 Position)
void initLights ()
void RenderText (Mesh *mesh, std::string text, Color color)
void RenderTextOnScreen (Mesh *mesh, std::string text, Color color, float size, float x, float y)
bool InteractionBoundsCheck (Vector3 CameraPosition, int value)
void initBounds ()
void renderParticleEmitter (GLuint Texture, Vector3 Direction, Vector3 Velocity, int ParticleCount, int Spread)
Private Attributes
GLuint SB_Day_front
GLuint SB_Day_back
GLuint SB_Day_top
GLuint SB_Day_bottom
GLuint SB_Day_left
GLuint SB_Day_right
GLuint SB_Nite_front
GLuint SB_Nite_back
GLuint SB_Nite_top
GLuint SB_Nite_bottom
GLuint SB_Nite_left
GLuint SB_Nite_right
unsigned m_vertexArrayID
unsigned m_programID
unsigned m_parameters [U_TOTAL]
Mesh * meshList [NUM_GEOMETRY]
bool canPlacePlank = false
bool plankPlaced = false
Boundary PlankIxB
bool canInteractWithKyogre = false
bool interactedWithKyogre = false
Boundary KyogreIxB
float framesPerSecond
Boundary DoorIxB
bool canOpenDoor = false
bool DoorOpened = false
Boundary LampIxB
bool canUseLamp = false
bool IsNight = false
bool LampActive = true
float timeCheck = 0
Vector3 TownLightPosition
Vector3 RoomLightPosition
Detailed Description
Definition at line 26 of file Particle.h.
Member Enumeration Documentation
enum Particle::GEOMETRY_TYPE private
Enumerator
GEO_AXES
GEO_QUAD
GEO_CUBE
GEO_CIRCLE
GEO_RING
GEO_SPHERE
GEO_HEMISPHERE
GEO_TORUS
GEO_CYLINDER
GEO_CONE
GEO_LEFT
GEO_RIGHT
GEO_TOP
GEO_BOTTOM
GEO_FRONT
GEO_BACK
GEO_SNIPER
GEO_TEXT
GEO_LIGHTBALL
GEO_FLOOR
NUM_GEOMETRY
Definition at line 28 of file Particle.h.
enum Particle::UNIFORM_TYPE private
Enumerator
U_MVP
U_MODELVIEW
U_MODELVIEW_INVERSE_TRANSPOSE
U_MATERIAL_AMBIENT
U_MATERIAL_DIFFUSE
U_MATERIAL_SPECULAR
U_MATERIAL_SHININESS
U_COLOR_TEXTURE_ENABLED
U_COLOR_TEXTURE
U_TEXT_ENABLED
U_TEXT_COLOR
U_LIGHT0_POSITION
U_LIGHT0_COLOR
U_LIGHT0_POWER
U_LIGHT0_KC
U_LIGHT0_KL
U_LIGHT0_KQ
U_LIGHTENABLED
U_LIGHT0_TYPE
U_LIGHT0_SPOTDIRECTION
U_LIGHT0_COSCUTOFF
U_LIGHT0_COSINNER
U_LIGHT0_EXPONENT
U_LIGHT1_POSITION
U_LIGHT1_COLOR
U_LIGHT1_POWER
U_LIGHT1_KC
U_LIGHT1_KL
U_LIGHT1_KQ
U_LIGHT1_TYPE
U_LIGHT1_SPOTDIRECTION
U_LIGHT1_COSCUTOFF
U_LIGHT1_COSINNER
U_LIGHT1_EXPONENT
U_LIGHT2_POSITION
U_LIGHT2_COLOR
U_LIGHT2_POWER
U_LIGHT2_KC
U_LIGHT2_KL
U_LIGHT2_KQ
U_LIGHT2_TYPE
U_LIGHT2_SPOTDIRECTION
U_LIGHT2_COSCUTOFF
U_LIGHT2_COSINNER
U_LIGHT2_EXPONENT
U_NUMLIGHTS
U_TOTAL
Definition at line 61 of file Particle.h.
Constructor & Destructor Documentation
Particle::Particle ()
Definition at line 10 of file Particle.cpp.
Particle::~Particle ()
Definition at line 14 of file Particle.cpp.
Member Function Documentation
void Particle::Exit () virtual
Implements Scene.
Definition at line 424 of file Particle.cpp.
References m_programID, and m_vertexArrayID.
void Particle::Init () virtual
Implements Scene.
Definition at line 18 of file Particle.cpp.
References camera, MeshBuilder::GenerateAxes(), MeshBuilder::GenerateCube(), MeshBuilder::GenerateQuad(), MeshBuilder::GenerateText(), GEO_AXES, GEO_BACK, GEO_BOTTOM, GEO_CUBE, GEO_FRONT, GEO_LEFT, GEO_QUAD, GEO_RIGHT, GEO_TEXT, GEO_TOP, Camera3::Init(), initLights(), MS::LoadMatrix(), LoadShaders(), LoadTGA(), m_parameters, m_programID, m_vertexArrayID, meshList, projectionStack, S_Height, S_Width, SB_Day_back, SB_Day_bottom, SB_Day_front, SB_Day_left, SB_Day_right, SB_Day_top, Mtx44::SetToPerspective(), Mesh::textureID, U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, U_TEXT_COLOR, and U_TEXT_ENABLED.
void Particle::initBounds () private
Definition at line 258 of file Particle.cpp.
void Particle::initLights () private
Definition at line 212 of file Particle.cpp.
References Light::color, Light::cosCutoff, Light::cosInner, Math::DegreeToRadian(), Light::exponent, Light::kC, Light::kL, Light::kQ, light, Light::LIGHT_DIRECTIONAL, lightDefaultPos, m_parameters, m_programID, Light::position, Light::power, Position::Set(), Color::Set(), Vector3::Set(), Light::spotDirection, Light::type, U_LIGHT0_COLOR, U_LIGHT0_COSCUTOFF, U_LIGHT0_COSINNER, U_LIGHT0_EXPONENT, U_LIGHT0_KC, U_LIGHT0_KL, U_LIGHT0_KQ, U_LIGHT0_POSITION, U_LIGHT0_POWER, U_LIGHT0_SPOTDIRECTION, U_LIGHT0_TYPE, U_LIGHTENABLED, U_NUMLIGHTS, Position::x, Position::y, and Position::z.
Referenced by Init().
bool Particle::InteractionBoundsCheck (Vector3 CameraPosition, int value) private
void Particle::Render (double dt) virtual
Implements Scene.
Definition at line 358 of file Particle.cpp.
References camera, GEO_AXES, GEO_QUAD, Camera3::getCameraPosition(), light, Light::LIGHT_DIRECTIONAL, Light::LIGHT_SPOT, MS::LoadIdentity(), MS::LookAt(), m_parameters, meshList, modelStack, MS::PopMatrix(), Camera::position, Light::position, MS::PushMatrix(), RenderMesh(), RenderSkybox(), skyboxID, Light::spotDirection, Camera::target, MS::Top(), U_LIGHT0_POSITION, U_LIGHT0_SPOTDIRECTION, U_LIGHT1_POSITION, U_LIGHT1_SPOTDIRECTION, Camera::up, viewStack, Position::x, Vector3::x, Position::y, Vector3::y, Position::z, and Vector3::z.
void Particle::RenderMesh (Mesh * mesh, bool enableLight)
Definition at line 169 of file Particle.cpp.
References Mtx44::a, Mtx44::GetInverse(), Mtx44::GetTranspose(), Material::kAmbient, Material::kDiffuse, Material::kShininess, Material::kSpecular, m_parameters, Mesh::material, modelStack, projectionStack, Component::r, Mesh::Render(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MATERIAL_AMBIENT, U_MATERIAL_DIFFUSE, U_MATERIAL_SHININESS, U_MATERIAL_SPECULAR, U_MODELVIEW, U_MODELVIEW_INVERSE_TRANSPOSE, U_MVP, and viewStack.
Referenced by Render(), renderParticleEmitter(), and RenderSkybox().
void Particle::renderParticleEmitter (GLuint Texture, Vector3 Direction, Vector3 Velocity, int ParticleCount, int Spread) private
Definition at line 342 of file Particle.cpp.
References GEO_CUBE, GEO_QUAD, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), and Mesh::textureID.
void Particle::RenderSkybox (Vector3 Position) private
Definition at line 286 of file Particle.cpp.
References GEO_BACK, GEO_BOTTOM, GEO_FRONT, GEO_LEFT, GEO_RIGHT, GEO_TOP, meshList, modelStack, MS::PopMatrix(), MS::PushMatrix(), RenderMesh(), MS::Rotate(), MS::Scale(), MS::Translate(), Vector3::x, and Vector3::z.
Referenced by Render().
void Particle::RenderText (Mesh * mesh, std::string text, Color color) private
Definition at line 97 of file Particle.cpp.
References Mtx44::a, m_parameters, modelStack, projectionStack, Color::r, Mesh::Render(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void Particle::RenderTextOnScreen (Mesh * mesh, std::string text, Color color, float size, float x, float y) private
Definition at line 125 of file Particle.cpp.
References Mtx44::a, MS::LoadIdentity(), MS::LoadMatrix(), m_parameters, modelStack, MS::PopMatrix(), projectionStack, MS::PushMatrix(), Color::r, Mesh::Render(), MS::Scale(), Mtx44::SetToOrtho(), Mtx44::SetToTranslation(), Mesh::textureID, MS::Top(), MS::Translate(), U_COLOR_TEXTURE, U_COLOR_TEXTURE_ENABLED, U_LIGHTENABLED, U_MVP, U_TEXT_COLOR, U_TEXT_ENABLED, and viewStack.
void Particle::Update (double dt) virtual
Implements Scene.
Definition at line 263 of file Particle.cpp.
References camera, framesPerSecond, Application::IsKeyPressed(), and Camera3::Update().
Field Documentation
Camera3 Particle::camera
Definition at line 153 of file Particle.h.
Referenced by Init(), Render(), and Update().
bool Particle::canInteractWithKyogre = false private
Definition at line 177 of file Particle.h.
bool Particle::canOpenDoor = false private
Definition at line 183 of file Particle.h.
bool Particle::canPlacePlank = false private
Definition at line 174 of file Particle.h.
bool Particle::canUseDoor = true
Definition at line 145 of file Particle.h.
bool Particle::canUseLamp = false private
Definition at line 187 of file Particle.h.
float Particle::constRotation
Definition at line 134 of file Particle.h.
float Particle::constTranslation
Definition at line 143 of file Particle.h.
Boundary Particle::DoorIxB private
Definition at line 182 of file Particle.h.
bool Particle::DoorOpened = false private
Definition at line 184 of file Particle.h.
float Particle::DoorRot
Definition at line 144 of file Particle.h.
float Particle::framesPerSecond private
Definition at line 181 of file Particle.h.
Referenced by Update().
bool Particle::interactedWithKyogre = false private
Definition at line 178 of file Particle.h.
bool Particle::IsNight = false private
Definition at line 188 of file Particle.h.
Boundary Particle::KyogreIxB private
Definition at line 179 of file Particle.h.
bool Particle::LampActive = true private
Definition at line 189 of file Particle.h.
Boundary Particle::LampIxB private
Definition at line 186 of file Particle.h.
Light Particle::light[3]
Definition at line 126 of file Particle.h.
Referenced by initLights(), and Render().
Position Particle::lightDefaultPos
Definition at line 149 of file Particle.h.
Referenced by initLights().
bool Particle::lightOff
Definition at line 151 of file Particle.h.
bool Particle::limitersON
Definition at line 142 of file Particle.h.
unsigned Particle::m_parameters[U_TOTAL] private
Definition at line 163 of file Particle.h.
Referenced by Init(), initLights(), Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
unsigned Particle::m_programID private
Definition at line 162 of file Particle.h.
Referenced by Exit(), Init(), and initLights().
unsigned Particle::m_vertexArrayID private
Definition at line 161 of file Particle.h.
Referenced by Exit(), and Init().
Mesh* Particle::meshList[NUM_GEOMETRY] private
Definition at line 164 of file Particle.h.
Referenced by Init(), Render(), renderParticleEmitter(), and RenderSkybox().
MS Particle::modelStack
Definition at line 155 of file Particle.h.
Referenced by Render(), RenderMesh(), renderParticleEmitter(), RenderSkybox(), RenderText(), and RenderTextOnScreen().
Boundary Particle::PlankIxB private
Definition at line 176 of file Particle.h.
bool Particle::plankPlaced = false private
Definition at line 175 of file Particle.h.
MS Particle::projectionStack
Definition at line 155 of file Particle.h.
Referenced by Init(), RenderMesh(), RenderText(), and RenderTextOnScreen().
bool Particle::rLimiter
Definition at line 140 of file Particle.h.
Vector3 Particle::RoomLightPosition private
Definition at line 194 of file Particle.h.
float Particle::rotationalLimit
Definition at line 137 of file Particle.h.
GLuint Particle::SB_Day_back private
Definition at line 158 of file Particle.h.
Referenced by Init().
GLuint Particle::SB_Day_bottom private
Definition at line 158 of file Particle.h.
Referenced by Init().
GLuint Particle::SB_Day_front private
Definition at line 158 of file Particle.h.
Referenced by Init().
GLuint Particle::SB_Day_left private
Definition at line 158 of file Particle.h.
Referenced by Init().
GLuint Particle::SB_Day_right private
Definition at line 158 of file Particle.h.
Referenced by Init().
GLuint Particle::SB_Day_top private
Definition at line 158 of file Particle.h.
Referenced by Init().
GLuint Particle::SB_Nite_back private
Definition at line 159 of file Particle.h.
GLuint Particle::SB_Nite_bottom private
Definition at line 159 of file Particle.h.
GLuint Particle::SB_Nite_front private
Definition at line 159 of file Particle.h.
GLuint Particle::SB_Nite_left private
Definition at line 159 of file Particle.h.
GLuint Particle::SB_Nite_right private
Definition at line 159 of file Particle.h.
GLuint Particle::SB_Nite_top private
Definition at line 159 of file Particle.h.
float Particle::scaleAll
Definition at line 136 of file Particle.h.
float Particle::scalingLimit
Definition at line 139 of file Particle.h.
unsigned short Particle::skyboxID = 0
Definition at line 147 of file Particle.h.
Referenced by Render().
float Particle::timeCheck = 0 private
Definition at line 190 of file Particle.h.
bool Particle::toggleLimiters
Definition at line 141 of file Particle.h.
Vector3 Particle::TownLightPosition private
Definition at line 193 of file Particle.h.
float Particle::translateX
Definition at line 135 of file Particle.h.
float Particle::translationLimit
Definition at line 138 of file Particle.h.
float Particle::tweenVal
Definition at line 133 of file Particle.h.
MS Particle::viewStack
Definition at line 155 of file Particle.h.
Referenced by Render(), RenderMesh(), RenderText(), and RenderTextOnScreen().
The documentation for this class was generated from the following files:
ComGLab/Source/Particle.h
ComGLab/Source/Particle.cpp