My Application: StopWatch Class Reference
StopWatch Class Reference
#include <timer.h>
Public Member Functions
StopWatch ()
~StopWatch ()
void startTimer ()
double getElapsedTime ()
void waitUntil (long long time)
Private Member Functions
double LIToSecs (LARGE_INTEGER &L)
Private Attributes
LARGE_INTEGER frequency
LARGE_INTEGER prevTime
LARGE_INTEGER currTime
UINT wTimerRes
Detailed Description
Definition at line 6 of file timer.h.
Constructor & Destructor Documentation
StopWatch::StopWatch ()
Definition at line 3 of file timer.cpp.
References frequency, TARGET_RESOLUTION, and wTimerRes.
StopWatch::~StopWatch ()
Definition at line 20 of file timer.cpp.
References wTimerRes.
Member Function Documentation
double StopWatch::getElapsedTime ()
Definition at line 34 of file timer.cpp.
References currTime, LIToSecs(), and prevTime.
Referenced by Application::Run().
double StopWatch::LIToSecs (LARGE_INTEGER & L) private
Definition at line 25 of file timer.cpp.
References frequency.
Referenced by getElapsedTime().
void StopWatch::startTimer ()
Definition at line 29 of file timer.cpp.
References prevTime.
Referenced by Application::Run().
void StopWatch::waitUntil (long long time)
Definition at line 43 of file timer.cpp.
References frequency, and prevTime.
Referenced by Application::Run().
Field Documentation
LARGE_INTEGER StopWatch::currTime private
Definition at line 12 of file timer.h.
Referenced by getElapsedTime().
LARGE_INTEGER StopWatch::frequency private
Definition at line 11 of file timer.h.
Referenced by LIToSecs(), StopWatch(), and waitUntil().
LARGE_INTEGER StopWatch::prevTime private
Definition at line 12 of file timer.h.
Referenced by getElapsedTime(), startTimer(), and waitUntil().
UINT StopWatch::wTimerRes private
Definition at line 14 of file timer.h.
Referenced by StopWatch(), and ~StopWatch().
The documentation for this class was generated from the following files:
Common/Source/timer.h
Common/Source/timer.cpp