My Application: Robot Class Reference
Robot Class Reference
#include <Robot.h>
Public Types
enum R_Type { Melee = 0, Ranged, Mixed }
Public Member Functions
Robot ()
Robot (int RobotType, float Rotation, Vector3 SpawnPos)
~Robot ()
Vector3 Move ()
void FindNewTarget ()
Vector3 Position ()
void BoundsCheck (WeaponSystem WepSys)
float GetHealth ()
void SetHealth (float newHP)
void RobotAnimation (double dt)
void CalcBounds ()
void SetShipTarget (Vector3 newTarget)
Data Fields
Boundary BoundingBox
float rotateToTarget
bool isMothership = false
float Rotation
float rotatelefthand = 0
float rotaterighthand = 0
float leftarmrotatelimit = -1
float rightarmrotatelimit = -1
bool leftarmrotate = true
bool rightarmrotate = true
float leftleglimit = 4
float rightleglimit = 4
float moveleftleg = 0
float moverightleg = 0
bool leftleg = true
bool rightleg = true
bool robotleftattack
bool robotrightattack
float rightarmattack = 0
float rightarmattacklimit = -4
float leftarmattack = 0
float leftarmattacklimit = -4
float collapse = 0
bool die = false
bool deadanimationover = false
Private Member Functions
Vector3 GetDirVec (Vector3 Target)
void SetStats (int Type)
Private Attributes
R_Type RobotType
float Damage
float Speed
float Health
int RobotTypeVal = 0
Vector3 TargetPos = (0, 0, 0)
Vector3 DirVec
Vector3 CurrPos
Detailed Description
Definition at line 10 of file Robot.h.
Member Enumeration Documentation
enum Robot::R_Type
Enumerator
Melee
Ranged
Mixed
Definition at line 14 of file Robot.h.
Constructor & Destructor Documentation
Robot::Robot ()
Robot::Robot (int RobotType, float Rotation, Vector3 SpawnPos)
Definition at line 5 of file Robot.cpp.
References CalcBounds(), CurrPos, GetDirVec(), RobotType, RobotTypeVal, Rotation, SetStats(), and TargetPos.
Robot::~Robot ()
Definition at line 17 of file Robot.cpp.
Member Function Documentation
void Robot::BoundsCheck (WeaponSystem WepSys)
Definition at line 83 of file Robot.cpp.
References Boundary::BoundaryCheck(), BoundingBox, WeaponSystem::BulletList, Health, and SetHealth().
void Robot::CalcBounds ()
Definition at line 206 of file Robot.cpp.
References BoundingBox, CurrPos, RobotTypeVal, Boundary::set(), Vector3::x, Vector3::y, and Vector3::z.
Referenced by Move(), and Robot().
void Robot::FindNewTarget ()
Definition at line 41 of file Robot.cpp.
References Boundary::BoundaryCheck(), CurrPos, isMothership, TargetPos, Vector3::x, Vector3::y, and Vector3::z.
Referenced by Move().
Vector3 Robot::GetDirVec (Vector3 Target) private
Definition at line 215 of file Robot.cpp.
References CurrPos, DirVec, Vector3::Length(), and Vector3::Normalize().
Referenced by Move(), and Robot().
float Robot::GetHealth ()
Definition at line 96 of file Robot.cpp.
References Health.
Referenced by Move().
Vector3 Robot::Move ()
Definition at line 23 of file Robot.cpp.
References CalcBounds(), CurrPos, die, DirVec, FindNewTarget(), GetDirVec(), GetHealth(), Speed, TargetPos, Vector3::x, Vector3::y, and Vector3::z.
Vector3 Robot::Position ()
Definition at line 78 of file Robot.cpp.
References CurrPos.
void Robot::RobotAnimation (double dt)
Definition at line 106 of file Robot.cpp.
References collapse, deadanimationover, die, leftarmrotate, leftarmrotatelimit, leftleg, leftleglimit, moveleftleg, moverightleg, rightarmrotate, rightarmrotatelimit, rightleg, rightleglimit, rotatelefthand, and rotaterighthand.
void Robot::SetHealth (float newHP)
Definition at line 101 of file Robot.cpp.
References Health.
Referenced by BoundsCheck().
void Robot::SetShipTarget (Vector3 newTarget)
Definition at line 73 of file Robot.cpp.
References TargetPos.
void Robot::SetStats (int Type) private
Definition at line 225 of file Robot.cpp.
References Damage, Health, Melee, RobotType, and Speed.
Referenced by Robot().
Field Documentation
Boundary Robot::BoundingBox
Definition at line 25 of file Robot.h.
Referenced by BoundsCheck(), and CalcBounds().
float Robot::collapse = 0
Definition at line 56 of file Robot.h.
Referenced by RobotAnimation().
Vector3 Robot::CurrPos private
Definition at line 72 of file Robot.h.
Referenced by CalcBounds(), FindNewTarget(), GetDirVec(), Move(), Position(), and Robot().
float Robot::Damage private
Definition at line 64 of file Robot.h.
Referenced by SetStats().
bool Robot::deadanimationover = false
Definition at line 58 of file Robot.h.
Referenced by RobotAnimation().
bool Robot::die = false
Definition at line 57 of file Robot.h.
Referenced by Move(), and RobotAnimation().
Vector3 Robot::DirVec private
Definition at line 71 of file Robot.h.
Referenced by GetDirVec(), and Move().
float Robot::Health private
Definition at line 66 of file Robot.h.
Referenced by BoundsCheck(), GetHealth(), SetHealth(), and SetStats().
bool Robot::isMothership = false
Definition at line 30 of file Robot.h.
Referenced by FindNewTarget().
float Robot::leftarmattack = 0
Definition at line 53 of file Robot.h.
float Robot::leftarmattacklimit = -4
Definition at line 54 of file Robot.h.
bool Robot::leftarmrotate = true
Definition at line 39 of file Robot.h.
Referenced by RobotAnimation().
float Robot::leftarmrotatelimit = -1
Definition at line 37 of file Robot.h.
Referenced by RobotAnimation().
bool Robot::leftleg = true
Definition at line 46 of file Robot.h.
Referenced by RobotAnimation().
float Robot::leftleglimit = 4
Definition at line 42 of file Robot.h.
Referenced by RobotAnimation().
float Robot::moveleftleg = 0
Definition at line 44 of file Robot.h.
Referenced by RobotAnimation().
float Robot::moverightleg = 0
Definition at line 45 of file Robot.h.
Referenced by RobotAnimation().
float Robot::rightarmattack = 0
Definition at line 51 of file Robot.h.
float Robot::rightarmattacklimit = -4
Definition at line 52 of file Robot.h.
bool Robot::rightarmrotate = true
Definition at line 40 of file Robot.h.
Referenced by RobotAnimation().
float Robot::rightarmrotatelimit = -1
Definition at line 38 of file Robot.h.
Referenced by RobotAnimation().
bool Robot::rightleg = true
Definition at line 47 of file Robot.h.
Referenced by RobotAnimation().
float Robot::rightleglimit = 4
Definition at line 43 of file Robot.h.
Referenced by RobotAnimation().
bool Robot::robotleftattack
Definition at line 49 of file Robot.h.
bool Robot::robotrightattack
Definition at line 50 of file Robot.h.
R_Type Robot::RobotType private
Definition at line 63 of file Robot.h.
Referenced by Robot(), and SetStats().
int Robot::RobotTypeVal = 0 private
Definition at line 67 of file Robot.h.
Referenced by CalcBounds(), and Robot().
float Robot::rotatelefthand = 0
Definition at line 35 of file Robot.h.
Referenced by RobotAnimation().
float Robot::rotaterighthand = 0
Definition at line 36 of file Robot.h.
Referenced by RobotAnimation().
float Robot::rotateToTarget
Definition at line 27 of file Robot.h.
float Robot::Rotation
Definition at line 34 of file Robot.h.
Referenced by Robot().
float Robot::Speed private
Definition at line 65 of file Robot.h.
Referenced by Move(), and SetStats().
Vector3 Robot::TargetPos = (0, 0, 0) private
Definition at line 70 of file Robot.h.
Referenced by FindNewTarget(), Move(), Robot(), and SetShipTarget().
The documentation for this class was generated from the following files:
ComGLab/Source/Robot.h
ComGLab/Source/Robot.cpp