My Application: Camera2 Class Reference
Camera2 Class Reference
#include <Camera2.h>
Public Member Functions
Camera2 ()
~Camera2 ()
virtual void Init (const Vector3 &pos, const Vector3 &target, const Vector3 &up)
virtual void Update (double dt)
virtual void Reset ()
Public Member Functions inherited from Camera
Camera ()
~Camera ()
Data Fields
Vector3 defaultPosition
Vector3 defaultTarget
Vector3 defaultUp
Data Fields inherited from Camera
Vector3 position
Vector3 target
Vector3 up
Detailed Description
Definition at line 6 of file Camera2.h.
Constructor & Destructor Documentation
Camera2::Camera2 ()
Definition at line 5 of file Camera2.cpp.
Camera2::~Camera2 ()
Definition at line 9 of file Camera2.cpp.
Member Function Documentation
void Camera2::Init (const Vector3 & pos, const Vector3 & target, const Vector3 & up) virtual
Reimplemented from Camera.
Definition at line 13 of file Camera2.cpp.
References Vector3::Cross(), defaultPosition, defaultTarget, defaultUp, Vector3::Normalize(), Vector3::Normalized(), Camera::position, Camera::target, and Vector3::y.
void Camera2::Reset () virtual
Reimplemented from Camera.
Definition at line 87 of file Camera2.cpp.
References defaultPosition, defaultTarget, defaultUp, Camera::position, Camera::target, and Camera::up.
Referenced by Update().
void Camera2::Update (double dt) virtual
Reimplemented from Camera.
Definition at line 24 of file Camera2.cpp.
References Vector3::Cross(), Application::IsKeyPressed(), Vector3::Length(), Vector3::Normalize(), Vector3::Normalized(), Camera::position, Reset(), Mtx44::SetToRotation(), Camera::target, Camera::up, Vector3::x, Vector3::y, and Vector3::z.
Field Documentation
Vector3 Camera2::defaultPosition
Definition at line 13 of file Camera2.h.
Referenced by Init(), and Reset().
Vector3 Camera2::defaultTarget
Definition at line 14 of file Camera2.h.
Referenced by Init(), and Reset().
Vector3 Camera2::defaultUp
Definition at line 15 of file Camera2.h.
Referenced by Init(), and Reset().
The documentation for this class was generated from the following files:
ComGLab/Source/Camera2.h
ComGLab/Source/Camera2.cpp