My Application: MeshBuilder Class Reference
MeshBuilder Class Reference
Provides methods to generate mesh of different shapes.
#include <MeshBuilder.h>
Public Member Functions
Mesh * GenerateParticle (const std::string &meshName, Color color)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Static Public Member Functions
static Mesh * GenerateAxes (const std::string &meshName, float lengthX, float lengthY, float lengthZ)
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateQuad (const std::string &meshName, Color color)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCube (const std::string &meshName, Color color)
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
static Mesh * GenerateCircle (const std::string &meshName, Color color, unsigned numSlices=36)
static Mesh * GenerateRing (const std::string &meshName, Color color, float outerRadius=1.2, float innerRadius=1.2, unsigned numSlices=36)
static Mesh * GenerateSphere (const std::string &meshName, Color color, unsigned numStacks=36, unsigned numSlices=36)
static Mesh * GenerateHemisphere (const std::string &meshName, Color color, unsigned numStacks=36, unsigned numSlices=36)
static Mesh * GenerateQuarterSphere (const std::string &meshName, Color color, unsigned numStacks=36, unsigned numSlices=36)
static Mesh * GenerateTorus (const std::string &meshName, Color color, float outerRadius=1, float innerRadius=1, unsigned numStacks=36, unsigned numSlices=36)
static Mesh * GenerateHalfTorus (const std::string &meshName, Color color, float outerRadius=1, float innerRadius=1, float numStacks=36, unsigned numSlices=36)
static Mesh * GenerateCylinder (const std::string &meshName, Color color, unsigned numStacks=36)
static Mesh * GenerateCone (const std::string &meshName, Color color, unsigned numStacks=36)
static Mesh * GenerateTrapezium (const std::string &meshName, Color color)
static Mesh * GeneratePrism (const std::string &meshName, Color color)
static Mesh * GenerateOBJ (const std::string &meshName, const std::string &file_path)
static Mesh * GenerateText (const std::string &meshName, unsigned numRow, unsigned numCol)
Detailed Description
Provides methods to generate mesh of different shapes.
Class MeshBuilder:
Definition at line 14 of file MeshBuilder.h.
Member Function Documentation
Mesh * MeshBuilder::GenerateAxes (const std::string & meshName, float lengthX, float lengthY, float lengthZ) static
Generate the vertices of a reference Axes; Use red for x-axis, green for y-axis, blue for z-axis Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - x-axis should start at -lengthX / 2 and end at lengthX / 2
lengthY - y-axis should start at -lengthY / 2 and end at lengthY / 2
lengthZ - z-axis should start at -lengthZ / 2 and end at lengthZ / 2
Returns
Pointer to mesh storing VBO/IBO of reference axes
Definition at line 17 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_LINES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::pos, Position::Set(), Color::Set(), and Mesh::vertexBuffer.
Referenced by Particle::Init(), and SP2_Scene::Init().
Mesh * MeshBuilder::GenerateCircle (const std::string & meshName, Color color, unsigned numSlices = 36) static
Definition at line 267 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SP2_Scene::Init().
Mesh * MeshBuilder::GenerateCone (const std::string & meshName, Color color, unsigned numStacks = 36) static
Definition at line 694 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vector3::Normalize(), Vertex::pos, Position::Set(), Vector3::Set(), Mesh::vertexBuffer, Position::x, and Position::z.
Referenced by SP2_Scene::Init().
Mesh * MeshBuilder::GenerateCube (const std::string & meshName, Color color) static
Generate the vertices of a cube; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of cube
lengthY - height of cube
lengthZ - depth of cube
Returns
Pointer to mesh storing VBO/IBO of cube
Definition at line 138 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by Particle::Init(), SP2_Scene::Init(), and SP2_Scene::InitRobots().
Mesh * MeshBuilder::GenerateCylinder (const std::string & meshName, Color color, unsigned numStacks = 36) static
Definition at line 623 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SP2_Scene::Init().
Mesh * MeshBuilder::GenerateHalfTorus (const std::string & meshName, Color color, float outerRadius = 1, float innerRadius = 1, float numStacks = 36, unsigned numSlices = 36) static
Definition at line 572 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateHemisphere (const std::string & meshName, Color color, unsigned numStacks = 36, unsigned numSlices = 36) static
Definition at line 479 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), Mesh::vertexBuffer, Position::x, Position::y, and Position::z.
Referenced by SP2_Scene::Init().
Mesh * MeshBuilder::GenerateOBJ (const std::string & meshName, const std::string & file_path) static
Definition at line 811 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, IndexVBO(), LoadOBJ(), Mesh::mode, and Mesh::vertexBuffer.
Referenced by SP2_Scene::InitMapModels(), SP2_Scene::InitRobots(), and SP2_Scene::InitWeaponModels().
Mesh * MeshBuilder::GenerateParticle (const std::string & meshName, Color color)
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 902 of file MeshBuilder.cpp.
Mesh * MeshBuilder::GeneratePrism (const std::string & meshName, Color color) static
Definition at line 204 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Mesh * MeshBuilder::GenerateQuad (const std::string & meshName, Color color) static
Generate the vertices of a quad; Use random color for each vertex Then generate the VBO/IBO and store them in Mesh object.
Parameters
meshName - name of mesh
lengthX - width of quad
lengthY - height of quad
Returns
Pointer to mesh storing VBO/IBO of quad
Definition at line 80 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by Particle::Init(), SP2_Scene::Init(), and SP2_Scene::initUIElements().
Mesh * MeshBuilder::GenerateQuarterSphere (const std::string & meshName, Color color, unsigned numStacks = 36, unsigned numSlices = 36) static
Definition at line 433 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), Mesh::vertexBuffer, Position::x, Position::y, and Position::z.
Mesh * MeshBuilder::GenerateRing (const std::string & meshName, Color color, float outerRadius = 1.2, float innerRadius = 1.2, unsigned numSlices = 36) static
Definition at line 315 of file MeshBuilder.cpp.
References CircleX(), CircleZ(), Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SP2_Scene::Init().
Mesh * MeshBuilder::GenerateSphere (const std::string & meshName, Color color, unsigned numStacks = 36, unsigned numSlices = 36) static
Definition at line 385 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), SphereX(), SphereY(), SphereZ(), Mesh::vertexBuffer, Position::x, Position::y, and Position::z.
Referenced by SP2_Scene::Init().
Mesh * MeshBuilder::GenerateText (const std::string & meshName, unsigned numRow, unsigned numCol) static
Definition at line 839 of file MeshBuilder.cpp.
References Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), TexCoord::Set(), Vector3::Set(), Vertex::texCoord, and Mesh::vertexBuffer.
Referenced by Particle::Init(), and SP2_Scene::initUIElements().
Mesh * MeshBuilder::GenerateTorus (const std::string & meshName, Color color, float outerRadius = 1, float innerRadius = 1, unsigned numStacks = 36, unsigned numSlices = 36) static
Definition at line 524 of file MeshBuilder.cpp.
References Vertex::color, Math::DegreeToRadian(), Mesh::DRAW_TRIANGLE_STRIP, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
Referenced by SP2_Scene::Init().
Mesh * MeshBuilder::GenerateTrapezium (const std::string & meshName, Color color) static
Definition at line 745 of file MeshBuilder.cpp.
References Vertex::color, Mesh::DRAW_TRIANGLES, Mesh::indexBuffer, Mesh::indexSize, Mesh::mode, Vertex::normal, Vertex::pos, Position::Set(), Vector3::Set(), and Mesh::vertexBuffer.
The documentation for this class was generated from the following files:
ComGLab/Source/MeshBuilder.h
ComGLab/Source/MeshBuilder.cpp