My Application: irrKlang-1.5.0/plugins/ikpMP3/decoder/mpaudec.c File Reference
mpaudec.c File Reference
#include "internal.h"
#include "mpegaudio.h"
#include "mpaudectab.h"
Data Structures
struct MPADecodeContext
struct GranuleDef
struct HuffTable
Macros
#define USE_HIGHPRECISION
#define FRAC_BITS 23 /* fractional bits for sb_samples and dct */
#define WFRAC_BITS 16 /* fractional bits for window */
#define FRAC_ONE (1 << FRAC_BITS)
#define MULL(a, b) (((int64_t)(a) * (int64_t)(b)) >> FRAC_BITS)
#define MUL64(a, b) ((int64_t)(a) * (int64_t)(b))
#define FIX(a) ((int)((a) * FRAC_ONE))
#define FIXR(a) ((int)((a) * FRAC_ONE + 0.5))
#define FRAC_RND(a) (((a) + (FRAC_ONE/2)) >> FRAC_BITS)
#define HEADER_SIZE 4
#define BACKSTEP_SIZE 512
#define MODE_EXT_MS_STEREO 2
#define MODE_EXT_I_STEREO 1
#define TABLE_4_3_SIZE (8191 + 16)
#define SCALE_GEN(v) { FIXR(1.0 * (v)), FIXR(0.7937005259 * (v)), FIXR(0.6299605249 * (v)) }
#define DEV_ORDER 13
#define POW_FRAC_BITS 24
#define POW_FRAC_ONE (1 << POW_FRAC_BITS)
#define POW_FIX(a) ((int)((a) * POW_FRAC_ONE))
#define POW_MULL(a, b) (((int64_t)(a) * (int64_t)(b)) >> POW_FRAC_BITS)
#define COS0_0 FIXR(0.50060299823519630134)
#define COS0_1 FIXR(0.50547095989754365998)
#define COS0_2 FIXR(0.51544730992262454697)
#define COS0_3 FIXR(0.53104259108978417447)
#define COS0_4 FIXR(0.55310389603444452782)
#define COS0_5 FIXR(0.58293496820613387367)
#define COS0_6 FIXR(0.62250412303566481615)
#define COS0_7 FIXR(0.67480834145500574602)
#define COS0_8 FIXR(0.74453627100229844977)
#define COS0_9 FIXR(0.83934964541552703873)
#define COS0_10 FIXR(0.97256823786196069369)
#define COS0_11 FIXR(1.16943993343288495515)
#define COS0_12 FIXR(1.48416461631416627724)
#define COS0_13 FIXR(2.05778100995341155085)
#define COS0_14 FIXR(3.40760841846871878570)
#define COS0_15 FIXR(10.19000812354805681150)
#define COS1_0 FIXR(0.50241928618815570551)
#define COS1_1 FIXR(0.52249861493968888062)
#define COS1_2 FIXR(0.56694403481635770368)
#define COS1_3 FIXR(0.64682178335999012954)
#define COS1_4 FIXR(0.78815462345125022473)
#define COS1_5 FIXR(1.06067768599034747134)
#define COS1_6 FIXR(1.72244709823833392782)
#define COS1_7 FIXR(5.10114861868916385802)
#define COS2_0 FIXR(0.50979557910415916894)
#define COS2_1 FIXR(0.60134488693504528054)
#define COS2_2 FIXR(0.89997622313641570463)
#define COS2_3 FIXR(2.56291544774150617881)
#define COS3_0 FIXR(0.54119610014619698439)
#define COS3_1 FIXR(1.30656296487637652785)
#define COS4_0 FIXR(0.70710678118654752439)
#define BF(a, b, c)
#define BF1(a, b, c, d)
#define BF2(a, b, c, d)
#define ADD(a, b) tab[a] += tab[b]
#define OUT_SHIFT (WFRAC_BITS + FRAC_BITS - 15)
#define MULS(ra, rb) MUL64(ra, rb)
#define SUM8(sum, op, w, p)
#define SUM8P2(sum1, op1, sum2, op2, w1, w2, p)
#define C1 FIXR(0.99144486137381041114)
#define C3 FIXR(0.92387953251128675612)
#define C5 FIXR(0.79335334029123516458)
#define C7 FIXR(0.60876142900872063941)
#define C9 FIXR(0.38268343236508977173)
#define C11 FIXR(0.13052619222005159154)
#define C1 FIXR(0.98480775301220805936)
#define C2 FIXR(0.93969262078590838405)
#define C3 FIXR(0.86602540378443864676)
#define C4 FIXR(0.76604444311897803520)
#define C5 FIXR(0.64278760968653932632)
#define C6 FIXR(0.5)
#define C7 FIXR(0.34202014332566873304)
#define C8 FIXR(0.17364817766693034885)
#define SAME_HEADER_MASK (0xffe00000 | (3 << 17) | (0xf << 12) | (3 << 10) | (3 << 19))
#define ISQRT2 FIXR(0.70710678118654752440)
Typedefs
typedef int32_t MPA_INT
typedef struct MPADecodeContext MPADecodeContext
typedef struct GranuleDef GranuleDef
typedef struct HuffTable HuffTable
Functions
static int l1_unscale (int n, int mant, int scale_factor)
static int l2_unscale_group (int steps, int mant, int scale_factor)
static int l3_unscale (int value, int exponent)
static void int_pow_init (void)
static int int_pow (int i, int *exp_ptr)
int mpaudec_init (MPAuDecContext *mpctx)
static void dct32 (int32_t *out, int32_t *tab)
static int round_sample (int64_t sum)
static void synth_filter (MPADecodeContext *s1, int ch, int16_t *samples, int incr, int32_t sb_samples[SBLIMIT])
static void imdct12 (int *out, int *in)
static void imdct36 (int *out, int *in)
static int check_header (uint32_t header)
static int decode_header (MPADecodeContext *s, uint32_t header)
static int mp_decode_layer1 (MPADecodeContext *s)
static int l2_select_table (int bitrate, int nb_channels, int freq, int lsf)
static int mp_decode_layer2 (MPADecodeContext *s)
static void seek_to_maindata (MPADecodeContext *s, unsigned int backstep)
static void lsf_sf_expand (int *slen, int sf, int n1, int n2, int n3)
static void exponents_from_scale_factors (MPADecodeContext *s, GranuleDef *g, int16_t *exponents)
static int get_bitsz (GetBitContext *s, int n)
static int huffman_decode (MPADecodeContext *s, GranuleDef *g, int16_t *exponents, int end_pos)
static void reorder_block (MPADecodeContext *s, GranuleDef *g)
static void compute_stereo (MPADecodeContext *s, GranuleDef *g0, GranuleDef *g1)
static void compute_antialias (MPADecodeContext *s, GranuleDef *g)
static void compute_imdct (MPADecodeContext *s, GranuleDef *g, int32_t *sb_samples, int32_t *mdct_buf)
static int mp_decode_layer3 (MPADecodeContext *s)
static int mp_decode_frame (MPADecodeContext *s, int16_t *samples)
int mpaudec_decode_frame (MPAuDecContext *mpctx, void *data, int *data_size, const uint8_t *buf, int buf_size)
void mpaudec_clear (MPAuDecContext *mpctx)
Variables
static VLC huff_vlc [16]
static uint8_t * huff_code_table [16]
static VLC huff_quad_vlc [2]
static uint16_t band_index_long [9][23]
static int8_t table_4_3_exp [TABLE_4_3_SIZE]
static uint32_t table_4_3_value [TABLE_4_3_SIZE]
static int32_t is_table [2][16]
static int32_t is_table_lsf [2][2][16]
static int32_t csa_table [8][2]
static int32_t mdct_win [8][36]
static uint16_t scale_factor_modshift [64]
static int32_t scale_factor_mult [15][3]
static int32_t scale_factor_mult2 [3][3]
static uint32_t scale_factor_mult3 [4]
static MPA_INT window [512]
static int dev_4_3_coefs [DEV_ORDER]
static int pow_mult3 [3]
static const int icos36 [9]
static const int icos72 [18]
Macro Definition Documentation
#define ADD (a, b) tab[a] += tab[b]
Definition at line 564 of file mpaudec.c.
Referenced by dct32().
#define BACKSTEP_SIZE 512
Definition at line 67 of file mpaudec.c.
Referenced by mpaudec_init(), and seek_to_maindata().
#define BF (a, b, c)
Value:
{\
    tmp0 = tab[a] + tab[b];\
    tmp1 = tab[a] - tab[b];\
    tab[a] = tmp0;\
    tab[b] = MULL(tmp1, c);\
}
Definition at line 539 of file mpaudec.c.
Referenced by dct32().
#define BF1 (a, b, c, d)
Value:
{\
    BF(a, b, COS4_0);\
    BF(c, d, -COS4_0);\
    tab[c] += tab[d];\
}
Definition at line 547 of file mpaudec.c.
Referenced by dct32().
#define BF2 (a, b, c, d)
Value:
{\
    BF(a, b, COS4_0);\
    BF(c, d, -COS4_0);\
    tab[c] += tab[d];\
    tab[a] += tab[c];\
    tab[c] += tab[b];\
    tab[b] += tab[d];\
}
Definition at line 554 of file mpaudec.c.
Referenced by dct32().
#define C1 FIXR(0.99144486137381041114)
Definition at line 929 of file mpaudec.c.
Referenced by imdct12(), and imdct36().
#define C1 FIXR(0.98480775301220805936)
Definition at line 929 of file mpaudec.c.
#define C11 FIXR(0.13052619222005159154)
Definition at line 881 of file mpaudec.c.
Referenced by imdct12().
#define C2 FIXR(0.93969262078590838405)
Definition at line 930 of file mpaudec.c.
Referenced by imdct36().
#define C3 FIXR(0.92387953251128675612)
Definition at line 931 of file mpaudec.c.
Referenced by imdct12(), and imdct36().
#define C3 FIXR(0.86602540378443864676)
Definition at line 931 of file mpaudec.c.
#define C4 FIXR(0.76604444311897803520)
Definition at line 932 of file mpaudec.c.
Referenced by imdct36().
#define C5 FIXR(0.79335334029123516458)
Definition at line 933 of file mpaudec.c.
Referenced by imdct12(), and imdct36().
#define C5 FIXR(0.64278760968653932632)
Definition at line 933 of file mpaudec.c.
#define C6 FIXR(0.5)
Definition at line 934 of file mpaudec.c.
Referenced by imdct36().
#define C7 FIXR(0.60876142900872063941)
Definition at line 935 of file mpaudec.c.
Referenced by imdct12(), and imdct36().
#define C7 FIXR(0.34202014332566873304)
Definition at line 935 of file mpaudec.c.
#define C8 FIXR(0.17364817766693034885)
Definition at line 936 of file mpaudec.c.
Referenced by imdct36().
#define C9 FIXR(0.38268343236508977173)
Definition at line 880 of file mpaudec.c.
Referenced by imdct12().
#define COS0_0 FIXR(0.50060299823519630134)
Definition at line 502 of file mpaudec.c.
Referenced by dct32().
#define COS0_1 FIXR(0.50547095989754365998)
Definition at line 503 of file mpaudec.c.
Referenced by dct32().
#define COS0_10 FIXR(0.97256823786196069369)
Definition at line 512 of file mpaudec.c.
Referenced by dct32().
#define COS0_11 FIXR(1.16943993343288495515)
Definition at line 513 of file mpaudec.c.
Referenced by dct32().
#define COS0_12 FIXR(1.48416461631416627724)
Definition at line 514 of file mpaudec.c.
Referenced by dct32().
#define COS0_13 FIXR(2.05778100995341155085)
Definition at line 515 of file mpaudec.c.
Referenced by dct32().
#define COS0_14 FIXR(3.40760841846871878570)
Definition at line 516 of file mpaudec.c.
Referenced by dct32().
#define COS0_15 FIXR(10.19000812354805681150)
Definition at line 517 of file mpaudec.c.
Referenced by dct32().
#define COS0_2 FIXR(0.51544730992262454697)
Definition at line 504 of file mpaudec.c.
Referenced by dct32().
#define COS0_3 FIXR(0.53104259108978417447)
Definition at line 505 of file mpaudec.c.
Referenced by dct32().
#define COS0_4 FIXR(0.55310389603444452782)
Definition at line 506 of file mpaudec.c.
Referenced by dct32().
#define COS0_5 FIXR(0.58293496820613387367)
Definition at line 507 of file mpaudec.c.
Referenced by dct32().
#define COS0_6 FIXR(0.62250412303566481615)
Definition at line 508 of file mpaudec.c.
Referenced by dct32().
#define COS0_7 FIXR(0.67480834145500574602)
Definition at line 509 of file mpaudec.c.
Referenced by dct32().
#define COS0_8 FIXR(0.74453627100229844977)
Definition at line 510 of file mpaudec.c.
Referenced by dct32().
#define COS0_9 FIXR(0.83934964541552703873)
Definition at line 511 of file mpaudec.c.
Referenced by dct32().
#define COS1_0 FIXR(0.50241928618815570551)
Definition at line 519 of file mpaudec.c.
Referenced by dct32().
#define COS1_1 FIXR(0.52249861493968888062)
Definition at line 520 of file mpaudec.c.
Referenced by dct32().
#define COS1_2 FIXR(0.56694403481635770368)
Definition at line 521 of file mpaudec.c.
Referenced by dct32().
#define COS1_3 FIXR(0.64682178335999012954)
Definition at line 522 of file mpaudec.c.
Referenced by dct32().
#define COS1_4 FIXR(0.78815462345125022473)
Definition at line 523 of file mpaudec.c.
Referenced by dct32().
#define COS1_5 FIXR(1.06067768599034747134)
Definition at line 524 of file mpaudec.c.
Referenced by dct32().
#define COS1_6 FIXR(1.72244709823833392782)
Definition at line 525 of file mpaudec.c.
Referenced by dct32().
#define COS1_7 FIXR(5.10114861868916385802)
Definition at line 526 of file mpaudec.c.
Referenced by dct32().
#define COS2_0 FIXR(0.50979557910415916894)
Definition at line 528 of file mpaudec.c.
Referenced by dct32().
#define COS2_1 FIXR(0.60134488693504528054)
Definition at line 529 of file mpaudec.c.
Referenced by dct32().
#define COS2_2 FIXR(0.89997622313641570463)
Definition at line 530 of file mpaudec.c.
Referenced by dct32().
#define COS2_3 FIXR(2.56291544774150617881)
Definition at line 531 of file mpaudec.c.
Referenced by dct32().
#define COS3_0 FIXR(0.54119610014619698439)
Definition at line 533 of file mpaudec.c.
Referenced by dct32().
#define COS3_1 FIXR(1.30656296487637652785)
Definition at line 534 of file mpaudec.c.
Referenced by dct32().
#define COS4_0 FIXR(0.70710678118654752439)
Definition at line 536 of file mpaudec.c.
#define DEV_ORDER 13
Definition at line 235 of file mpaudec.c.
Referenced by int_pow(), and int_pow_init().
#define FIX (a) ((int)((a) * FRAC_ONE))
Definition at line 53 of file mpaudec.c.
Referenced by mpaudec_init().
#define FIXR (a) ((int)((a) * FRAC_ONE + 0.5))
Definition at line 55 of file mpaudec.c.
Referenced by mpaudec_init().
#define FRAC_BITS 23 /* fractional bits for sb_samples and dct */
Definition at line 42 of file mpaudec.c.
Referenced by int_pow(), and l3_unscale().
#define FRAC_ONE (1 << FRAC_BITS)
Definition at line 49 of file mpaudec.c.
Referenced by mp_decode_frame(), and mpaudec_init().
#define FRAC_RND (a) (((a) + (FRAC_ONE/2)) >> FRAC_BITS)
Definition at line 56 of file mpaudec.c.
Referenced by compute_antialias(), imdct12(), and imdct36().
#define HEADER_SIZE 4
Definition at line 66 of file mpaudec.c.
Referenced by mp_decode_frame(), and mpaudec_decode_frame().
#define ISQRT2 FIXR(0.70710678118654752440)
Definition at line 1699 of file mpaudec.c.
Referenced by compute_stereo().
#define MODE_EXT_I_STEREO 1
Definition at line 118 of file mpaudec.c.
Referenced by compute_stereo(), decode_header(), and mp_decode_layer3().
#define MODE_EXT_MS_STEREO 2
Definition at line 117 of file mpaudec.c.
Referenced by compute_stereo(), decode_header(), and mp_decode_layer3().
#define MUL64 (a, b) ((int64_t)(a) * (int64_t)(b))
Definition at line 52 of file mpaudec.c.
Referenced by compute_antialias(), imdct12(), imdct36(), l1_unscale(), and l3_unscale().
#define MULL (a, b) (((int64_t)(a) * (int64_t)(b)) >> FRAC_BITS)
Definition at line 51 of file mpaudec.c.
Referenced by compute_imdct(), compute_stereo(), imdct36(), and mpaudec_init().
#define MULS (ra, rb) MUL64(ra, rb)
Definition at line 751 of file mpaudec.c.
#define OUT_SHIFT (WFRAC_BITS + FRAC_BITS - 15)
Definition at line 717 of file mpaudec.c.
Referenced by round_sample().
#define POW_FIX (a) ((int)((a) * POW_FRAC_ONE))
Definition at line 239 of file mpaudec.c.
Referenced by int_pow_init().
#define POW_FRAC_BITS 24
Definition at line 237 of file mpaudec.c.
Referenced by int_pow().
#define POW_FRAC_ONE (1 << POW_FRAC_BITS)
Definition at line 238 of file mpaudec.c.
Referenced by int_pow().
#define POW_MULL (a, b) (((int64_t)(a) * (int64_t)(b)) >> POW_FRAC_BITS)
Definition at line 240 of file mpaudec.c.
Referenced by int_pow(), and int_pow_init().
#define SAME_HEADER_MASK (0xffe00000 | (3 << 17) | (0xf << 12) | (3 << 10) | (3 << 19))
Definition at line 1073 of file mpaudec.c.
Referenced by mpaudec_decode_frame().
#define SCALE_GEN (v) { FIXR(1.0 * (v)), FIXR(0.7937005259 * (v)), FIXR(0.6299605249 * (v)) }
Definition at line 155 of file mpaudec.c.
#define SUM8 (sum, op, w, p)
Value:
{                                               \
    sum op MULS((w)[0 * 64], p[0 * 64]);\
    sum op MULS((w)[1 * 64], p[1 * 64]);\
    sum op MULS((w)[2 * 64], p[2 * 64]);\
    sum op MULS((w)[3 * 64], p[3 * 64]);\
    sum op MULS((w)[4 * 64], p[4 * 64]);\
    sum op MULS((w)[5 * 64], p[5 * 64]);\
    sum op MULS((w)[6 * 64], p[6 * 64]);\
    sum op MULS((w)[7 * 64], p[7 * 64]);\
}
Definition at line 755 of file mpaudec.c.
Referenced by synth_filter().
#define SUM8P2 (sum1, op1, sum2, op2, w1, w2, p)
Value:
{                                               \
    int tmp;\
    tmp = p[0 * 64];\
    sum1 op1 MULS((w1)[0 * 64], tmp);\
    sum2 op2 MULS((w2)[0 * 64], tmp);\
    tmp = p[1 * 64];\
    sum1 op1 MULS((w1)[1 * 64], tmp);\
    sum2 op2 MULS((w2)[1 * 64], tmp);\
    tmp = p[2 * 64];\
    sum1 op1 MULS((w1)[2 * 64], tmp);\
    sum2 op2 MULS((w2)[2 * 64], tmp);\
    tmp = p[3 * 64];\
    sum1 op1 MULS((w1)[3 * 64], tmp);\
    sum2 op2 MULS((w2)[3 * 64], tmp);\
    tmp = p[4 * 64];\
    sum1 op1 MULS((w1)[4 * 64], tmp);\
    sum2 op2 MULS((w2)[4 * 64], tmp);\
    tmp = p[5 * 64];\
    sum1 op1 MULS((w1)[5 * 64], tmp);\
    sum2 op2 MULS((w2)[5 * 64], tmp);\
    tmp = p[6 * 64];\
    sum1 op1 MULS((w1)[6 * 64], tmp);\
    sum2 op2 MULS((w2)[6 * 64], tmp);\
    tmp = p[7 * 64];\
    sum1 op1 MULS((w1)[7 * 64], tmp);\
    sum2 op2 MULS((w2)[7 * 64], tmp);\
}
Definition at line 767 of file mpaudec.c.
Referenced by synth_filter().
#define TABLE_4_3_SIZE (8191 + 16)
Definition at line 136 of file mpaudec.c.
Referenced by mpaudec_init().
#define USE_HIGHPRECISION
Definition at line 39 of file mpaudec.c.
#define WFRAC_BITS 16 /* fractional bits for window */
Definition at line 43 of file mpaudec.c.
Referenced by mpaudec_init().
Typedef Documentation
typedef struct GranuleDef GranuleDef
typedef struct HuffTable HuffTable
typedef int32_t MPA_INT
Definition at line 61 of file mpaudec.c.
typedef struct MPADecodeContext MPADecodeContext
Function Documentation
static int check_header (uint32_t header) static
Definition at line 1055 of file mpaudec.c.
Referenced by mpaudec_decode_frame().
static void compute_antialias (MPADecodeContext * s, GranuleDef * g) static
Definition at line 1828 of file mpaudec.c.
References GranuleDef::block_type, csa_table, FRAC_RND, MUL64, GranuleDef::sb_hybrid, SBLIMIT, and GranuleDef::switch_point.
Referenced by mp_decode_layer3().
static void compute_imdct (MPADecodeContext * s, GranuleDef * g, int32_t * sb_samples, int32_t * mdct_buf) static
Definition at line 1862 of file mpaudec.c.
References GranuleDef::block_type, imdct12(), imdct36(), mdct_win, MULL, GranuleDef::sb_hybrid, SBLIMIT, and GranuleDef::switch_point.
Referenced by mp_decode_layer3().
static void compute_stereo (MPADecodeContext * s, GranuleDef * g0, GranuleDef * g1) static
Definition at line 1701 of file mpaudec.c.
References band_size_long, band_size_short, is_table, is_table_lsf, ISQRT2, GranuleDef::long_end, MPADecodeContext::lsf, MPADecodeContext::mode_ext, MODE_EXT_I_STEREO, MODE_EXT_MS_STEREO, MULL, MPADecodeContext::sample_rate_index, GranuleDef::sb_hybrid, GranuleDef::scale_factors, GranuleDef::scalefac_compress, and GranuleDef::short_start.
Referenced by mp_decode_layer3().
static void dct32 (int32_t * out, int32_t * tab) static
Definition at line 567 of file mpaudec.c.
References ADD, BF, BF1, BF2, COS0_0, COS0_1, COS0_10, COS0_11, COS0_12, COS0_13, COS0_14, COS0_15, COS0_2, COS0_3, COS0_4, COS0_5, COS0_6, COS0_7, COS0_8, COS0_9, COS1_0, COS1_1, COS1_2, COS1_3, COS1_4, COS1_5, COS1_6, COS1_7, COS2_0, COS2_1, COS2_2, COS2_3, COS3_0, and COS3_1.
Referenced by synth_filter().
static int decode_header (MPADecodeContext * s, uint32_t header) static
Definition at line 1079 of file mpaudec.c.
References MPADecodeContext::bit_rate, MPADecodeContext::error_protection, MPADecodeContext::frame_size, MPADecodeContext::free_format_frame_size, MPADecodeContext::layer, MPADecodeContext::lsf, MPADecodeContext::mode, MPADecodeContext::mode_ext, MODE_EXT_I_STEREO, MODE_EXT_MS_STEREO, mpa_bitrate_tab, mpa_freq_tab, MPA_MONO, MPADecodeContext::nb_channels, MPADecodeContext::sample_rate, and MPADecodeContext::sample_rate_index.
Referenced by mpaudec_decode_frame().
static void exponents_from_scale_factors (MPADecodeContext * s, GranuleDef * g, int16_t * exponents) static
Definition at line 1512 of file mpaudec.c.
References band_size_long, band_size_short, GranuleDef::global_gain, GranuleDef::long_end, mpa_pretab, GranuleDef::preflag, MPADecodeContext::sample_rate_index, GranuleDef::scale_factors, GranuleDef::scalefac_scale, GranuleDef::short_start, and GranuleDef::subblock_gain.
Referenced by mp_decode_layer3().
static int get_bitsz (GetBitContext * s, int n) static
Definition at line 1551 of file mpaudec.c.
References get_bits().
Referenced by huffman_decode(), and mp_decode_layer3().
static int huffman_decode (MPADecodeContext * s, GranuleDef * g, int16_t * exponents, int end_pos) static
Definition at line 1559 of file mpaudec.c.
References GetBitContext::buffer, GranuleDef::count1table_select, MPADecodeContext::gb, get_bits(), get_bits_count(), get_bitsz(), get_vlc(), huff_code_table, l3_unscale(), mpa_huff_data, GranuleDef::region_size, GranuleDef::sb_hybrid, and GranuleDef::table_select.
Referenced by mp_decode_layer3().
static void imdct12 (int * out, int * in) static
Definition at line 885 of file mpaudec.c.
References C1, C11, C3, C5, C7, C9, FRAC_RND, and MUL64.
Referenced by compute_imdct().
static void imdct36 (int * out, int * in) static
Definition at line 976 of file mpaudec.c.
References C1, C2, C3, C4, C5, C6, C7, C8, FRAC_RND, icos36, icos72, MUL64, and MULL.
Referenced by compute_imdct().
static int int_pow (int i, int * exp_ptr) static
Definition at line 262 of file mpaudec.c.
References dev_4_3_coefs, DEV_ORDER, FRAC_BITS, POW_FRAC_BITS, POW_FRAC_ONE, POW_MULL, and pow_mult3.
Referenced by mpaudec_init().
static void int_pow_init (void) static
Definition at line 250 of file mpaudec.c.
References dev_4_3_coefs, DEV_ORDER, POW_FIX, and POW_MULL.
Referenced by mpaudec_init().
static int l1_unscale (int n, int mant, int scale_factor) static
Definition at line 176 of file mpaudec.c.
References MUL64, scale_factor_modshift, and scale_factor_mult.
Referenced by mp_decode_layer1(), and mp_decode_layer2().
static int l2_select_table (int bitrate, int nb_channels, int freq, int lsf) static
Definition at line 1240 of file mpaudec.c.
Referenced by mp_decode_layer2().
static int l2_unscale_group (int steps, int mant, int scale_factor) static
Definition at line 190 of file mpaudec.c.
References scale_factor_modshift, and scale_factor_mult2.
Referenced by mp_decode_layer2().
static int l3_unscale (int value, int exponent) static
Definition at line 206 of file mpaudec.c.
References FRAC_BITS, MUL64, scale_factor_mult3, table_4_3_exp, and table_4_3_value.
Referenced by huffman_decode().
static void lsf_sf_expand (int * slen, int sf, int n1, int n2, int n3) static
Definition at line 1492 of file mpaudec.c.
Referenced by mp_decode_layer3().
static int mp_decode_frame (MPADecodeContext * s, int16_t * samples) static
Definition at line 2258 of file mpaudec.c.
References MPADecodeContext::error_protection, FRAC_ONE, MPADecodeContext::gb, get_bits(), HEADER_SIZE, MPADecodeContext::inbuf, MPADecodeContext::inbuf_ptr, init_get_bits(), MPADecodeContext::layer, mp_decode_layer1(), mp_decode_layer2(), mp_decode_layer3(), MPADecodeContext::nb_channels, MPADecodeContext::sb_samples, SBLIMIT, and synth_filter().
Referenced by mpaudec_decode_frame().
static int mp_decode_layer1 (MPADecodeContext * s) static
Definition at line 1173 of file mpaudec.c.
References MPADecodeContext::gb, get_bits(), l1_unscale(), MPADecodeContext::mode, MPADecodeContext::mode_ext, MPA_JSTEREO, MPA_MAX_CHANNELS, MPADecodeContext::nb_channels, MPADecodeContext::sb_samples, and SBLIMIT.
Referenced by mp_decode_frame().
static int mp_decode_layer2 (MPADecodeContext * s) static
Definition at line 1261 of file mpaudec.c.
References alloc_table(), alloc_tables, MPADecodeContext::bit_rate, MPADecodeContext::gb, get_bits(), l1_unscale(), l2_select_table(), l2_unscale_group(), MPADecodeContext::lsf, MPADecodeContext::mode, MPADecodeContext::mode_ext, MPA_JSTEREO, MPA_MAX_CHANNELS, MPADecodeContext::nb_channels, quant_bits, quant_steps, MPADecodeContext::sample_rate, MPADecodeContext::sb_samples, SBLIMIT, and sblimit_table.
Referenced by mp_decode_frame().
static int mp_decode_layer3 (MPADecodeContext * s) static
Definition at line 1963 of file mpaudec.c.
References band_index_long, GranuleDef::big_values, GranuleDef::block_type, compute_antialias(), compute_imdct(), compute_stereo(), GranuleDef::count1table_select, exponents_from_scale_factors(), MPADecodeContext::gb, get_bits(), get_bits_count(), get_bitsz(), GranuleDef::global_gain, huffman_decode(), GranuleDef::long_end, MPADecodeContext::lsf, lsf_nsf_table, lsf_sf_expand(), MPADecodeContext::mdct_buf, MPADecodeContext::mode_ext, MODE_EXT_I_STEREO, MODE_EXT_MS_STEREO, MPADecodeContext::nb_channels, GranuleDef::part2_3_length, GranuleDef::preflag, GranuleDef::region_size, reorder_block(), MPADecodeContext::sample_rate_index, MPADecodeContext::sb_samples, GranuleDef::scale_factors, GranuleDef::scalefac_compress, GranuleDef::scalefac_scale, GranuleDef::scfsi, seek_to_maindata(), GranuleDef::short_start, skip_bits(), slen_table, GranuleDef::subblock_gain, GranuleDef::switch_point, and GranuleDef::table_select.
Referenced by mp_decode_frame().
void mpaudec_clear (MPAuDecContext * mpctx)
Definition at line 2472 of file mpaudec.c.
References MPAuDecContext::priv_data.
Referenced by irrklang::CIrrKlangAudioStreamMP3::setPosition(), and irrklang::CIrrKlangAudioStreamMP3::~CIrrKlangAudioStreamMP3().
int mpaudec_decode_frame (MPAuDecContext * mpctx, void * data, int * data_size, const uint8_t * buf, int buf_size)
Definition at line 2312 of file mpaudec.c.
References MPAuDecContext::bit_rate, MPADecodeContext::bit_rate, MPAuDecContext::channels, check_header(), MPAuDecContext::coded_frame_size, decode_header(), MPAuDecContext::frame_size, MPADecodeContext::frame_size, MPADecodeContext::free_format_frame_size, HEADER_SIZE, MPADecodeContext::inbuf, MPADecodeContext::inbuf_ptr, MPAuDecContext::layer, MPADecodeContext::layer, MPADecodeContext::lsf, mp_decode_frame(), MPA_MAX_CODED_FRAME_SIZE, MPADecodeContext::nb_channels, MPAuDecContext::parse_only, MPAuDecContext::priv_data, SAME_HEADER_MASK, MPAuDecContext::sample_rate, and MPADecodeContext::sample_rate.
Referenced by irrklang::CIrrKlangAudioStreamMP3::decodeFrame().
int mpaudec_init (MPAuDecContext * mpctx)
Definition at line 306 of file mpaudec.c.
References BACKSTEP_SIZE, band_index_long, band_size_long, HuffTable::bits, ci_table, HuffTable::codes, csa_table, FIX, FIXR, FRAC_ONE, huff_code_table, MPADecodeContext::inbuf, MPADecodeContext::inbuf1, MPADecodeContext::inbuf_index, MPADecodeContext::inbuf_ptr, init_vlc(), int_pow(), int_pow_init(), is_table, is_table_lsf, M_PI, mdct_win, mpa_enwindow, mpa_huff_tables, mpa_quad_bits, mpa_quad_codes, MULL, MPAuDecContext::parse_only, MPAuDecContext::priv_data, scale_factor_modshift, scale_factor_mult, table_4_3_exp, TABLE_4_3_SIZE, table_4_3_value, WFRAC_BITS, window, and HuffTable::xsize.
Referenced by irrklang::CIrrKlangAudioStreamMP3::CIrrKlangAudioStreamMP3(), and irrklang::CIrrKlangAudioStreamMP3::setPosition().
static void reorder_block (MPADecodeContext * s, GranuleDef * g) static
Definition at line 1666 of file mpaudec.c.
References band_size_short, GranuleDef::block_type, MPADecodeContext::sample_rate_index, GranuleDef::sb_hybrid, GranuleDef::short_start, and GranuleDef::switch_point.
Referenced by mp_decode_layer3().
static int round_sample (int64_t sum) static
Definition at line 740 of file mpaudec.c.
References OUT_SHIFT.
Referenced by synth_filter().
static void seek_to_maindata (MPADecodeContext * s, unsigned int backstep) static
Definition at line 1472 of file mpaudec.c.
References BACKSTEP_SIZE, GetBitContext::buffer, MPADecodeContext::frame_size, MPADecodeContext::gb, get_bits_count(), MPADecodeContext::inbuf, MPADecodeContext::inbuf1, MPADecodeContext::inbuf_index, init_get_bits(), and MPADecodeContext::old_frame_size.
Referenced by mp_decode_layer3().
static void synth_filter (MPADecodeContext * s1, int ch, int16_t * samples, int incr, int32_t sb_samples[SBLIMIT]) static
Definition at line 800 of file mpaudec.c.
References dct32(), round_sample(), SUM8, SUM8P2, MPADecodeContext::synth_buf, MPADecodeContext::synth_buf_offset, and window.
Referenced by mp_decode_frame().
Variable Documentation
uint16_t band_index_long[9][23] static
Definition at line 134 of file mpaudec.c.
Referenced by mp_decode_layer3(), and mpaudec_init().
int32_t csa_table[8][2] static
Definition at line 146 of file mpaudec.c.
Referenced by compute_antialias(), and mpaudec_init().
int dev_4_3_coefs[DEV_ORDER] static
Definition at line 242 of file mpaudec.c.
Referenced by int_pow(), and int_pow_init().
uint8_t* huff_code_table[16] static
Definition at line 131 of file mpaudec.c.
Referenced by huffman_decode(), and mpaudec_init().
VLC huff_quad_vlc[2] static
Definition at line 132 of file mpaudec.c.
VLC huff_vlc[16] static
Definition at line 130 of file mpaudec.c.
const int icos36[9] static
Initial value:
= {
    FIXR(0.50190991877167369479),
    FIXR(0.51763809020504152469),
    FIXR(0.55168895948124587824),
    FIXR(0.61038729438072803416),
    FIXR(0.70710678118654752439),
    FIXR(0.87172339781054900991),
    FIXR(1.18310079157624925896),
    FIXR(1.93185165257813657349),
    FIXR(5.73685662283492756461),
}
Definition at line 939 of file mpaudec.c.
Referenced by imdct36().
const int icos72[18] static
Initial value:
= {
    FIXR(0.74009361646113053152),
    FIXR(0.82133981585229078570),
    FIXR(0.93057949835178895673),
    FIXR(1.08284028510010010928),
    FIXR(1.30656296487637652785),
    FIXR(1.66275476171152078719),
    FIXR(2.31011315767264929558),
    FIXR(3.83064878777019433457),
    FIXR(11.46279281302667383546),
    FIXR(-0.67817085245462840086),
    FIXR(-0.63023620700513223342),
    FIXR(-0.59284452371708034528),
    FIXR(-0.56369097343317117734),
    FIXR(-0.54119610014619698439),
    FIXR(-0.52426456257040533932),
    FIXR(-0.51213975715725461845),
    FIXR(-0.50431448029007636036),
    FIXR(-0.50047634258165998492),
}
Definition at line 951 of file mpaudec.c.
Referenced by imdct36().
int32_t is_table[2][16] static
Definition at line 144 of file mpaudec.c.
Referenced by compute_stereo(), and mpaudec_init().
int32_t is_table_lsf[2][2][16] static
Definition at line 145 of file mpaudec.c.
Referenced by compute_stereo(), and mpaudec_init().
int32_t mdct_win[8][36] static
Definition at line 147 of file mpaudec.c.
Referenced by compute_imdct(), and mpaudec_init().
int pow_mult3[3] static
Initial value:
= {
    POW_FIX(1.0),
    POW_FIX(1.25992104989487316476),
    POW_FIX(1.58740105196819947474),
}
Definition at line 244 of file mpaudec.c.
Referenced by int_pow().
uint16_t scale_factor_modshift[64] static
Definition at line 150 of file mpaudec.c.
Referenced by l1_unscale(), l2_unscale_group(), and mpaudec_init().
int32_t scale_factor_mult[15][3] static
Definition at line 152 of file mpaudec.c.
Referenced by l1_unscale(), and mpaudec_init().
int32_t scale_factor_mult2[3][3] static
Initial value:
= {
    SCALE_GEN(4.0 / 3.0),
    SCALE_GEN(4.0 / 5.0),
    SCALE_GEN(4.0 / 9.0),
}
Definition at line 158 of file mpaudec.c.
Referenced by l2_unscale_group().
uint32_t scale_factor_mult3[4] static
Initial value:
= {
    FIXR(1.0),
    FIXR(1.18920711500272106671),
    FIXR(1.41421356237309504880),
    FIXR(1.68179283050742908605),
}
Definition at line 165 of file mpaudec.c.
Referenced by l3_unscale().
int8_t table_4_3_exp[TABLE_4_3_SIZE] static
Definition at line 137 of file mpaudec.c.
Referenced by l3_unscale(), and mpaudec_init().
uint32_t table_4_3_value[TABLE_4_3_SIZE] static
Definition at line 141 of file mpaudec.c.
Referenced by l3_unscale(), and mpaudec_init().
MPA_INT window[512] static
Definition at line 172 of file mpaudec.c.
Referenced by mpaudec_init(), and synth_filter().