My Application: irrKlang-1.5.0/plugins/ikpMP3/decoder/mpaudec.h File Reference
mpaudec.h File Reference
Data Structures
struct MPAuDecContext
Macros
#define MPAUDEC_MAX_AUDIO_FRAME_SIZE 4608
Typedefs
typedef struct MPAuDecContext MPAuDecContext
Functions
int mpaudec_init (MPAuDecContext *mpctx)
int mpaudec_decode_frame (MPAuDecContext *mpctx, void *data, int *data_size, const unsigned char *buf, int buf_size)
void mpaudec_clear (MPAuDecContext *mpctx)
Macro Definition Documentation
#define MPAUDEC_MAX_AUDIO_FRAME_SIZE 4608
Definition at line 11 of file mpaudec.h.
Referenced by irrklang::CIrrKlangAudioStreamMP3::CIrrKlangAudioStreamMP3().
Typedef Documentation
typedef struct MPAuDecContext MPAuDecContext
Function Documentation
void mpaudec_clear (MPAuDecContext * mpctx)
Definition at line 2472 of file mpaudec.c.
References MPAuDecContext::priv_data.
Referenced by irrklang::CIrrKlangAudioStreamMP3::setPosition(), and irrklang::CIrrKlangAudioStreamMP3::~CIrrKlangAudioStreamMP3().
int mpaudec_decode_frame (MPAuDecContext * mpctx, void * data, int * data_size, const unsigned char * buf, int buf_size)
int mpaudec_init (MPAuDecContext * mpctx)
Definition at line 306 of file mpaudec.c.
References BACKSTEP_SIZE, band_index_long, band_size_long, HuffTable::bits, ci_table, HuffTable::codes, csa_table, FIX, FIXR, FRAC_ONE, huff_code_table, MPADecodeContext::inbuf, MPADecodeContext::inbuf1, MPADecodeContext::inbuf_index, MPADecodeContext::inbuf_ptr, init_vlc(), int_pow(), int_pow_init(), is_table, is_table_lsf, M_PI, mdct_win, mpa_enwindow, mpa_huff_tables, mpa_quad_bits, mpa_quad_codes, MULL, MPAuDecContext::parse_only, MPAuDecContext::priv_data, scale_factor_modshift, scale_factor_mult, table_4_3_exp, TABLE_4_3_SIZE, table_4_3_value, WFRAC_BITS, window, and HuffTable::xsize.
Referenced by irrklang::CIrrKlangAudioStreamMP3::CIrrKlangAudioStreamMP3(), and irrklang::CIrrKlangAudioStreamMP3::setPosition().