My Application: Boundary Struct Reference
Boundary Struct Reference
Defines 3D vectors and its methods.
#include <Boundary.h>
Public Member Functions
Boundary (float xMin=0, float xMax=0, float zMin=0, float zMax=0, float yMin=0, float yMax=0, unsigned short type=0)
Boundary (const Boundary &bound)
void set (float xMin=0, float xMax=0, float zMin=0, float zMax=0, float yMin=0, float yMax=0)
Sets the minimum and maximum x,y and z boundaries.
bool BoundaryCheck (const float &playerCoordX, const float &playerCoordZ, const float &playerCoordY)
Checks if the players position is outside of the boundaries set.
Data Fields
float xMin
float xMax
float zMin
float zMax
float yMin
float yMax
unsigned short type
bool active = true
bool isWithin = false
Detailed Description
Defines 3D vectors and its methods.
Struct Boundary:
Definition at line 21 of file Boundary.h.
Constructor & Destructor Documentation
Boundary::Boundary (float xMin = 0, float xMax = 0, float zMin = 0, float zMax = 0, float yMin = 0, float yMax = 0, unsigned short type = 0) inline
Definition at line 23 of file Boundary.h.
Boundary::Boundary (const Boundary & bound) inline
Definition at line 24 of file Boundary.h.
Member Function Documentation
bool Boundary::BoundaryCheck (const float & playerCoordX, const float & playerCoordZ, const float & playerCoordY)
Checks if the players position is outside of the boundaries set.
Parameters
xMin - miminum point for x-axis xMax - maximum point for x-axis zMin - minimum point for z-axis zMax - maxinum point for z-axis yMin - minimum point for y-axis yMax - maximum point for y-axis playerCoordX - Player's position on the x-axis playerCoordZ - Player's position on the z-axis playerCoordY - Player's position on the y-axis
Returns
Returns false if player is outside of the boundaries
Definition at line 58 of file Boundary.cpp.
References xMax, xMin, yMax, yMin, zMax, and zMin.
Referenced by Robot::BoundsCheck(), Camera3::cameraMovement2(), Robot::FindNewTarget(), SP2_Scene::RenderPowerUp(), Camera3::Update(), and SP2_Scene::Update().
void Boundary::set (float xMin = 0, float xMax = 0, float zMin = 0, float zMax = 0, float yMin = 0, float yMax = 0)
Sets the minimum and maximum x,y and z boundaries.
Parameters
xMin - miminum point for x-axis xMax - maximum point for x-axis zMin - minimum point for z-axis zMax - maxinum point for z-axis yMin - minimum point for y-axis yMax - maximum point for y-axis
Returns
values for boundaries
Definition at line 29 of file Boundary.cpp.
References xMax, xMin, yMax, yMin, zMax, and zMin.
Referenced by RayCast::CalcBounds(), Robot::CalcBounds(), Camera3::initBoundVec(), and SP2_Scene::Update().
Field Documentation
bool Boundary::active = true
Definition at line 28 of file Boundary.h.
bool Boundary::isWithin = false
Definition at line 29 of file Boundary.h.
unsigned short Boundary::type
Definition at line 27 of file Boundary.h.
float Boundary::xMax
Definition at line 24 of file Boundary.h.
Referenced by BoundaryCheck(), and set().
float Boundary::xMin
Definition at line 24 of file Boundary.h.
Referenced by BoundaryCheck(), and set().
float Boundary::yMax
Definition at line 24 of file Boundary.h.
Referenced by BoundaryCheck(), and set().
float Boundary::yMin
Definition at line 24 of file Boundary.h.
Referenced by BoundaryCheck(), and set().
float Boundary::zMax
Definition at line 24 of file Boundary.h.
Referenced by BoundaryCheck(), and set().
float Boundary::zMin
Definition at line 24 of file Boundary.h.
Referenced by BoundaryCheck(), and set().
The documentation for this struct was generated from the following files:
ComGLab/Source/Boundary.h
ComGLab/Source/Boundary.cpp