My Application: irrklang::SAudioStreamFormat Struct Reference
irrklang::SAudioStreamFormat Struct Reference
structure describing an audio stream format with helper functions
#include <ik_SAudioStreamFormat.h>
Public Member Functions
ik_s32 getSampleSize () const
returns the size of a sample of the data described by the stream data in bytes
ik_s32 getFrameSize () const
returns the frame size of the stream data in bytes
ik_s32 getSampleDataSize () const
returns the size of the sample data in bytes
ik_s32 getBytesPerSecond () const
returns amount of bytes per second
Data Fields
ik_s32 ChannelCount
channels, 1 for mono, 2 for stereo
ik_s32 FrameCount
amount of frames in the sample data or stream.
ik_s32 SampleRate
samples per second
ESampleFormat SampleFormat
format of the sample data
Detailed Description
structure describing an audio stream format with helper functions
Definition at line 26 of file ik_SAudioStreamFormat.h.
Member Function Documentation
ik_s32 irrklang::SAudioStreamFormat::getBytesPerSecond () const inline
returns amount of bytes per second
Definition at line 61 of file ik_SAudioStreamFormat.h.
References getFrameSize(), and SampleRate.
ik_s32 irrklang::SAudioStreamFormat::getFrameSize () const inline
returns the frame size of the stream data in bytes
Definition at line 48 of file ik_SAudioStreamFormat.h.
References getSampleSize().
Referenced by irrklang::CIrrKlangAudioStreamMP3::decodeFrame(), getBytesPerSecond(), getSampleDataSize(), irrklang::CIrrKlangAudioStreamMP3::readFrames(), and irrklang::CIrrKlangAudioStreamMP3::setPosition().
ik_s32 irrklang::SAudioStreamFormat::getSampleDataSize () const inline
returns the size of the sample data in bytes
Definition at line 55 of file ik_SAudioStreamFormat.h.
References FrameCount, and getFrameSize().
ik_s32 irrklang::SAudioStreamFormat::getSampleSize () const inline
returns the size of a sample of the data described by the stream data in bytes
Definition at line 42 of file ik_SAudioStreamFormat.h.
References irrklang::ESF_U8.
Referenced by getFrameSize().
Field Documentation
ik_s32 irrklang::SAudioStreamFormat::ChannelCount
channels, 1 for mono, 2 for stereo
Definition at line 29 of file ik_SAudioStreamFormat.h.
Referenced by irrklang::CIrrKlangAudioStreamMP3::decodeFrame().
ik_s32 irrklang::SAudioStreamFormat::FrameCount
amount of frames in the sample data or stream.
If the stream has an unknown lenght, this is -1
Definition at line 33 of file ik_SAudioStreamFormat.h.
Referenced by irrklang::CIrrKlangAudioStreamMP3::CIrrKlangAudioStreamMP3(), irrklang::CIrrKlangAudioStreamMP3::decodeFrame(), and getSampleDataSize().
ESampleFormat irrklang::SAudioStreamFormat::SampleFormat
format of the sample data
Definition at line 39 of file ik_SAudioStreamFormat.h.
Referenced by irrklang::CIrrKlangAudioStreamMP3::decodeFrame().
ik_s32 irrklang::SAudioStreamFormat::SampleRate
samples per second
Definition at line 36 of file ik_SAudioStreamFormat.h.
Referenced by irrklang::CIrrKlangAudioStreamMP3::decodeFrame(), and getBytesPerSecond().
The documentation for this struct was generated from the following file:
irrKlang-1.5.0/include/ik_SAudioStreamFormat.h